/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examenes;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JTabbedPane;
import java.awt.BorderLayout;
import java.awt.Button;
import java.awt.Toolkit;
import java.io.File;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.application.Platform;
import javafx.embed.swing.JFXPanel;
import javafx.scene.Group;
import javafx.scene.Scene;
import javafx.scene.media.Media;
import javafx.scene.media.MediaPlayer;
import javafx.scene.media.MediaView;
import javafx.util.Duration;

/**
 *
 * @author javie
 */
public class Frmexamen extends javax.swing.JFrame {
    int Posicion =0;
    String NumeroVideo =null;
    JFXPanel jfxPanel1 = new JFXPanel();  
    JFXPanel jfxPanel2 = new JFXPanel();  
    JFXPanel jfxPanel3 = new JFXPanel();
    JFXPanel jfxPanel4 = new JFXPanel();
    JFXPanel jfxPanel5 = new JFXPanel();

    public static MediaPlayer oracleVid1;
    public static MediaPlayer oracleVid2;
    public static MediaPlayer oracleVid3;
    public static MediaPlayer oracleVid4;
    public static MediaPlayer oracleVid5;
    
    public Frmexamen() {
        
        //JbMax.setEnabled(false);
        
        initComponents();
        
        //JBPlay1.setContentAreaFilled(false);
       // JBPlay1.setOpaque(false);
        setLocationRelativeTo(null);
        //setTitle("Java Swing Video con FX");
        setResizable(false);
        //setLocationRelativeTo(null);
        //JBVideo1.setOpaque(false);
        //JBVideo1.setContentAreaFilled(false);
        //JBVideo1.setBorderPainted(false);
       
        
        
        //JPanelVideo1.add(jfxPanel1,BorderLayout.CENTER); 
        
        JPanelVideo2.setLayout(new BorderLayout());
        JPanelVideo2.add(jfxPanel2,BorderLayout.CENTER);
        
        JPanelVideo3.setLayout(new BorderLayout());
        JPanelVideo3.add(jfxPanel3,BorderLayout.CENTER);
        
        JPanelVideo4.setLayout(new BorderLayout());
        JPanelVideo4.add(jfxPanel4,BorderLayout.CENTER);
        
        JPanelVideo5.setLayout(new BorderLayout());
        JPanelVideo5.add(jfxPanel5,BorderLayout.CENTER);
       
        
       
        
        
    }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    
 
    


    
    public String obtenerMinutos(int val) {
        int horas = 0;
        int minutos = 0;

        while (val > 59) {
            if (val > 59) {
                val -= 60;
                minutos++;
            }
            if (minutos > 59) {
                minutos -= 60;
                horas++;
            }
        }
        String hor = horas + "";
        String min = minutos + "";
        String sec = val + "";
        if (horas < 10) {
            hor = "0" + hor;
        }
        if (minutos < 10) {
            min = "0" + min;
        }
        if (val < 10) {
            sec = "0" + sec;
        }
        return hor + ":" + min + ":" + sec;
    }

    
    
    
    
    
    
    
  
     
     
     
     @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPanelFondo = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        JPanelVideo1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        JPanelVideo2 = new javax.swing.JPanel();
        JPanelVideo3 = new javax.swing.JPanel();
        JPanelVideo4 = new javax.swing.JPanel();
        JPanelVideo5 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JPanelFondo.setBackground(new java.awt.Color(255, 255, 255));
        JPanelFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JPanelVideo1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setText("jLabel1");
        jLabel10.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel10MouseDragged(evt);
            }
        });
        JPanelVideo1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 100, 50));

        jTabbedPane1.addTab("tab1", JPanelVideo1);

        JPanelVideo2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jTabbedPane1.addTab("tab2", JPanelVideo2);

        JPanelVideo3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jTabbedPane1.addTab("tab3", JPanelVideo3);

        JPanelVideo4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jTabbedPane1.addTab("tab4", JPanelVideo4);

        JPanelVideo5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jTabbedPane1.addTab("tab5", JPanelVideo5);

        JPanelFondo.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, 480, 380));

        getContentPane().add(JPanelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel10MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseDragged
       JPanelVideo1.setLayout(new BorderLayout());
        jLabel10.setLocation(jLabel10.getLocation().x+ evt.getX() - jLabel10.getWidth()/2,
                jLabel10.getLocation().y+ evt.getY() - jLabel10.getHeight());
            //jLabel10.setLocation(evt.getPoint());
            //jLabel10.repaint();
    }//GEN-LAST:event_jLabel10MouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frmexamen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frmexamen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frmexamen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frmexamen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frmexamen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPanelFondo;
    private javax.swing.JPanel JPanelVideo1;
    private javax.swing.JPanel JPanelVideo2;
    private javax.swing.JPanel JPanelVideo3;
    private javax.swing.JPanel JPanelVideo4;
    private javax.swing.JPanel JPanelVideo5;
    private javax.swing.JLabel jLabel10;
    public static javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
