/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examenes;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;

/**
 *
 * @author javie
 */
public final class FrmModulos extends javax.swing.JFrame {

    /**
     * Creates new form FrmModulos
     */
    public FrmModulos() {
        
        
        initComponents();
         setLocationRelativeTo(null);
        rsscalelabel.RSScaleLabel.setScaleLabel(jLabel1,"src/imagenes/mate.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(jLabel2,"src/imagenes/socia.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(jLabel3,"src/imagenes/lengua.png");
        
        
       
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        JBLenguaje = new javax.swing.JButton();
        JBSociales = new javax.swing.JButton();
        JBMatematicas = new javax.swing.JButton();
        LbUser = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JBLenguaje.setText("presiona para empezar!");
        JBLenguaje.setAutoscrolls(true);
        JBLenguaje.setBorder(null);
        JBLenguaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBLenguajeActionPerformed(evt);
            }
        });
        jPanel1.add(JBLenguaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 570, 190, 40));

        JBSociales.setText("presiona para empezar!");
        JBSociales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBSocialesActionPerformed(evt);
            }
        });
        jPanel1.add(JBSociales, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 300, 160, 40));

        JBMatematicas.setText("presiona para empezar!");
        JBMatematicas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBMatematicasActionPerformed(evt);
            }
        });
        jPanel1.add(JBMatematicas, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 290, 160, 40));

        LbUser.setText("usuario");
        jPanel1.add(LbUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 10, 60, 30));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 240, 210));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 60, 260, 220));
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 330, 270, 220));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBMatematicasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBMatematicasActionPerformed
      FrmMatematicas v = new  FrmMatematicas();
      v.setVisible(true);
      v.setLocationRelativeTo(null);
      this.dispose();
    }//GEN-LAST:event_JBMatematicasActionPerformed

    private void JBSocialesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBSocialesActionPerformed
       FrmSociales v = new FrmSociales();
       v.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_JBSocialesActionPerformed

    private void JBLenguajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBLenguajeActionPerformed
        FrmLenguaje v = new FrmLenguaje();
        v.setVisible(true);
        v.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_JBLenguajeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmModulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmModulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmModulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmModulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new FrmModulos().setVisible(true);
        });
    }
    
    public Icon setIcon(String url, JButton boton){
    
        ImageIcon icon = new ImageIcon( getClass().getResource(url));
        
        int ancho = boton.getWidth();
        int alto = boton.getHeight();
        
        ImageIcon icono = new ImageIcon(icon.getImage().getScaledInstance(ancho,alto,Image.SCALE_DEFAULT));
        
        return icono;
      
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBLenguaje;
    private javax.swing.JButton JBMatematicas;
    private javax.swing.JButton JBSociales;
    public static javax.swing.JLabel LbUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
