/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package examenes;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.event.MouseEvent;

/**
 *
 * @author javie
 */
public class FrmMatematicas extends javax.swing.JFrame {

    /** Creates new form FrmLenguaje */
    public FrmMatematicas() {
        
        initComponents();
        setLocationRelativeTo(null);
       
        rsscalelabel.RSScaleLabel.setScaleLabel(JLImagen1,"src/imagenes/crucigrama.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(JL1_2,"src/imagenes/1-2.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(JL1_3,"src/imagenes/1_3.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(JL2_3,"src/imagenes/2_3.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(JL2_4,"src/imagenes/2_4.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(JL3_4,"src/imagenes/3_4.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(JLNaranja,"src/imagenes/naranja.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(JLLeche,"src/imagenes/leche.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(JLCono,"src/imagenes/cono.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(JLPiramide,"src/imagenes/pirámide.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(JLN1,"src/imagenes/4.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(JLN2,"src/imagenes/8.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(JLN3,"src/imagenes/2.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(JLN4,"src/imagenes/5.png");
        
         rsscalelabel.RSScaleLabel.setScaleLabel(JLTriangulo1,"src/imagenes/EQUILATERO.png");
         rsscalelabel.RSScaleLabel.setScaleLabel(JLTriangulo2,"src/imagenes/Isosceles.png");
         rsscalelabel.RSScaleLabel.setScaleLabel(JLTriangulo3,"src/imagenes/Escaleno.png");
        
     
        
    }
    // nota 1
    int notafinal1 =0;
    int A1=0;
    int A2=0;
    int A3=0;
    int A4=0;
    int A5=0;
    //nota 2
    int notafinal2=0;
    int B1=0;
    int B2=0;
    int B3=0;
    int B4=0;
    
    //nota 3
    int notafinal3=0;
    int C1=0;
    int C2=0;
    int C3=0;
    int C4=0;
    
    
     //nota 4
    int notafinal4=0;
    int D1=0;
    int D2=0;
    int D3=0;
    int D4=0;
    
    //nota 5
    int notafinal5=0;
    int E1=0;
    int E2=0;
    int E3=0;
    int E4=0;
    
    //nota 6
    int notafinal6=0;
    int F1=0;
    int F2=0;
    int F3=0;
    
    
        
        

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        JB3 = new javax.swing.JButton();
        JB4 = new javax.swing.JButton();
        JB5 = new javax.swing.JButton();
        JB6 = new javax.swing.JButton();
        JB7 = new javax.swing.JButton();
        JB8 = new javax.swing.JButton();
        JB9 = new javax.swing.JButton();
        JB1 = new javax.swing.JButton();
        JB2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        JLNota1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        JB10 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        JLPregunta1 = new javax.swing.JLabel();
        JLActividad1 = new javax.swing.JLabel();
        JPN3 = new javax.swing.JPanel();
        JL = new javax.swing.JLabel();
        JPN4 = new javax.swing.JPanel();
        JL1 = new javax.swing.JLabel();
        JPN5 = new javax.swing.JPanel();
        JL2 = new javax.swing.JLabel();
        JPN6 = new javax.swing.JPanel();
        JL3 = new javax.swing.JLabel();
        JPN2 = new javax.swing.JPanel();
        JL4 = new javax.swing.JLabel();
        JPN12 = new javax.swing.JPanel();
        JL5 = new javax.swing.JLabel();
        JLImagen1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        JLPregunta2 = new javax.swing.JLabel();
        JLActividad2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        JL1_2 = new javax.swing.JLabel();
        JL1_3 = new javax.swing.JLabel();
        JL2_3 = new javax.swing.JLabel();
        JL2_4 = new javax.swing.JLabel();
        JL3_4 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        JLActividad3 = new javax.swing.JLabel();
        JLPregunta3 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        JLPiramide = new javax.swing.JLabel();
        JLCono = new javax.swing.JLabel();
        JLLeche = new javax.swing.JLabel();
        JLNaranja = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        JLActividad4 = new javax.swing.JLabel();
        JLPregunta4 = new javax.swing.JLabel();
        JP1 = new javax.swing.JPanel();
        JB2P1 = new javax.swing.JButton();
        JB3P1 = new javax.swing.JButton();
        JLN1 = new javax.swing.JLabel();
        JB1P1 = new javax.swing.JButton();
        JP2 = new javax.swing.JPanel();
        JB2P2 = new javax.swing.JButton();
        JB3P2 = new javax.swing.JButton();
        JB1P2 = new javax.swing.JButton();
        JLN2 = new javax.swing.JLabel();
        JP3 = new javax.swing.JPanel();
        JB2P3 = new javax.swing.JButton();
        JB3P3 = new javax.swing.JButton();
        JB1P3 = new javax.swing.JButton();
        JLN3 = new javax.swing.JLabel();
        JP4 = new javax.swing.JPanel();
        JB2P4 = new javax.swing.JButton();
        JB3P4 = new javax.swing.JButton();
        JB1P4 = new javax.swing.JButton();
        JLN4 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        JLPregunta5 = new javax.swing.JLabel();
        JLActividad5 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        CB1 = new javax.swing.JComboBox<>();
        jPanel17 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        CB2 = new javax.swing.JComboBox<>();
        jPanel18 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jPanel19 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        CB4 = new javax.swing.JComboBox<>();
        jPanel20 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jPanel21 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        CB3 = new javax.swing.JComboBox<>();
        jPanel22 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        JLPregunta6 = new javax.swing.JLabel();
        JLActividad6 = new javax.swing.JLabel();
        JLTriangulo1 = new javax.swing.JLabel();
        JLTriangulo2 = new javax.swing.JLabel();
        JLTriangulo3 = new javax.swing.JLabel();
        JBT1 = new javax.swing.JButton();
        JBT5 = new javax.swing.JButton();
        JBT2 = new javax.swing.JButton();
        JBT4 = new javax.swing.JButton();
        JBT3 = new javax.swing.JButton();
        jPanel15 = new javax.swing.JPanel();
        JPT3 = new javax.swing.JPanel();
        JPT2 = new javax.swing.JPanel();
        JPT1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        JLNota2 = new javax.swing.JLabel();
        JLNota3 = new javax.swing.JLabel();
        JLNota4 = new javax.swing.JLabel();
        JLNota5 = new javax.swing.JLabel();
        JLNota6 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JB3.setText("Actividad # 3");
        jPanel1.add(JB3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 110, 30));

        JB4.setText("Actividad # 4");
        jPanel1.add(JB4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 110, 30));

        JB5.setText("Actividad # 5");
        jPanel1.add(JB5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 110, 30));

        JB6.setText("Actividad # 6");
        jPanel1.add(JB6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 110, 30));

        JB7.setText("Actividad # 7");
        jPanel1.add(JB7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 110, 30));

        JB8.setText("Actividad # 8");
        jPanel1.add(JB8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 110, 30));

        JB9.setText("Actividad # 9");
        jPanel1.add(JB9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 500, 110, 30));

        JB1.setText("Actividad # 1");
        JB1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                JB1MouseDragged(evt);
            }
        });
        jPanel1.add(JB1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 110, 30));

        JB2.setText("Actividad # 2");
        jPanel1.add(JB2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 110, 30));

        jLabel1.setText("listado de actividades");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 120, 40));

        JLNota1.setText("jLabel2");
        jPanel1.add(JLNota1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 60, 30));

        jLabel3.setText("jLabel3");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 70, 40));

        JB10.setText("Actividad # 10");
        jPanel1.add(JB10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 540, 110, 30));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JLPregunta1.setText("Arrastre el resultado correcto hacia la casilla que corresponda");
        jPanel2.add(JLPregunta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 49, -1, 25));

        JLActividad1.setText("Actividad #1");
        jPanel2.add(JLActividad1, new org.netbeans.lib.awtextra.AbsoluteConstraints(427, 11, 77, 27));

        JPN3.setBackground(new java.awt.Color(255, 175, 150));
        JPN3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                JPN3MouseDragged(evt);
            }
        });
        JPN3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                JPN3MouseReleased(evt);
            }
        });
        JPN3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JL.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        JL.setText("3");
        JPN3.add(JL, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 20, 30));

        jPanel2.add(JPN3, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 100, 40, 40));

        JPN4.setBackground(new java.awt.Color(255, 175, 150));
        JPN4.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                JPN4MouseDragged(evt);
            }
        });
        JPN4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                JPN4MouseReleased(evt);
            }
        });
        JPN4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JL1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        JL1.setText("4");
        JPN4.add(JL1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 20, 30));

        jPanel2.add(JPN4, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 100, 40, 40));

        JPN5.setBackground(new java.awt.Color(255, 175, 150));
        JPN5.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                JPN5MouseDragged(evt);
            }
        });
        JPN5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                JPN5MouseReleased(evt);
            }
        });
        JPN5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JL2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        JL2.setText("5");
        JPN5.add(JL2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 20, 30));

        jPanel2.add(JPN5, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 160, 40, 40));

        JPN6.setBackground(new java.awt.Color(255, 175, 150));
        JPN6.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                JPN6MouseDragged(evt);
            }
        });
        JPN6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                JPN6MouseReleased(evt);
            }
        });
        JPN6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JL3.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        JL3.setText("6");
        JPN6.add(JL3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 20, 30));

        jPanel2.add(JPN6, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 160, 40, 40));

        JPN2.setBackground(new java.awt.Color(255, 175, 150));
        JPN2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                JPN2MouseDragged(evt);
            }
        });
        JPN2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                JPN2MouseReleased(evt);
            }
        });
        JPN2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JL4.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        JL4.setText("2");
        JPN2.add(JL4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 20, 30));

        jPanel2.add(JPN2, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 220, 40, 40));

        JPN12.setBackground(new java.awt.Color(255, 175, 150));
        JPN12.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                JPN12MouseDragged(evt);
            }
        });
        JPN12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                JPN12MouseReleased(evt);
            }
        });
        JPN12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JL5.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        JL5.setText("12");
        JPN12.add(JL5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 40));

        jPanel2.add(JPN12, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 220, 40, 40));
        jPanel2.add(JLImagen1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 590, 570));

        jTabbedPane1.addTab("tab1", jPanel2);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JLPregunta2.setText("Arrastre la figura correcta hacia la fracción que corresponda");
        jPanel3.add(JLPregunta2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 49, -1, 25));

        JLActividad2.setText("Actividad #2");
        jPanel3.add(JLActividad2, new org.netbeans.lib.awtextra.AbsoluteConstraints(427, 11, 77, 27));

        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 150, 130));

        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 150, 130));

        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 150, 130));

        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 520, 150, 130));

        JL1_2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                JL1_2MouseDragged(evt);
            }
        });
        JL1_2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                JL1_2MouseReleased(evt);
            }
        });
        jPanel3.add(JL1_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 290, 100, 90));

        JL1_3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                JL1_3MouseDragged(evt);
            }
        });
        JL1_3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                JL1_3MouseReleased(evt);
            }
        });
        jPanel3.add(JL1_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 450, 100, 90));

        JL2_3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                JL2_3MouseDragged(evt);
            }
        });
        JL2_3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                JL2_3MouseReleased(evt);
            }
        });
        jPanel3.add(JL2_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 290, 100, 90));

        JL2_4.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                JL2_4MouseDragged(evt);
            }
        });
        JL2_4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                JL2_4MouseReleased(evt);
            }
        });
        jPanel3.add(JL2_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 450, 100, 90));

        JL3_4.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                JL3_4MouseDragged(evt);
            }
        });
        JL3_4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                JL3_4MouseReleased(evt);
            }
        });
        jPanel3.add(JL3_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 380, 100, 90));

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel20.setText("    1/2");
        jLabel20.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, 160, 130));

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel21.setText("    2/3");
        jLabel21.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 240, 160, 130));

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel22.setText("    1/3");
        jLabel22.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 380, 160, 130));

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel23.setText("    2/4");
        jLabel23.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 520, 160, 130));

        jTabbedPane1.addTab("tab2", jPanel3);

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JLActividad3.setText("Actividad #3");
        jPanel4.add(JLActividad3, new org.netbeans.lib.awtextra.AbsoluteConstraints(427, 11, 77, 27));

        JLPregunta3.setText("Identifica el cuerpo geométrico que tiene cada imagen y coloca la respuesta correcta.");
        jPanel4.add(JLPregunta3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 49, -1, 25));

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel26.setText("  PRISMA");
        jLabel26.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel26.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel26MouseDragged(evt);
            }
        });
        jLabel26.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel26MouseReleased(evt);
            }
        });
        jPanel4.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 350, 120, 40));

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel27.setText(" PIRAMIDE");
        jLabel27.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel27.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel27MouseDragged(evt);
            }
        });
        jLabel27.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel27MouseReleased(evt);
            }
        });
        jPanel4.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 550, 120, 40));

        jLabel30.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel30.setText("  ESFERA");
        jLabel30.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel30.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel30MouseDragged(evt);
            }
        });
        jLabel30.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel30MouseReleased(evt);
            }
        });
        jPanel4.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 250, 120, 40));

        jLabel31.setBackground(new java.awt.Color(255, 204, 102));
        jLabel31.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel31.setText("   CONO");
        jLabel31.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel31.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel31MouseDragged(evt);
            }
        });
        jLabel31.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel31MouseReleased(evt);
            }
        });
        jPanel4.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 140, 120, 40));

        JLPiramide.setText("jLabel8");
        jPanel4.add(JLPiramide, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 110, 110));

        JLCono.setText("jLabel8");
        jPanel4.add(JLCono, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 110, 110));

        JLLeche.setText("jLabel8");
        jPanel4.add(JLLeche, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 360, 110, 110));

        JLNaranja.setText("jLabel8");
        jPanel4.add(JLNaranja, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 490, 110, 110));

        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel28.setText("    CUBO");
        jLabel28.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel28.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel28MouseDragged(evt);
            }
        });
        jLabel28.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel28MouseReleased(evt);
            }
        });
        jPanel4.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 460, 120, 40));

        jPanel11.setBackground(new java.awt.Color(255, 204, 102));
        jPanel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, 230, 90));

        jPanel12.setBackground(new java.awt.Color(255, 204, 102));
        jPanel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 240, 230, 90));

        jPanel13.setBackground(new java.awt.Color(255, 204, 102));
        jPanel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 380, 230, 90));

        jPanel10.setBackground(new java.awt.Color(255, 204, 102));
        jPanel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 510, 230, 90));

        jTabbedPane1.addTab("tab3", jPanel4);

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JLActividad4.setText("Actividad #4");
        jPanel5.add(JLActividad4, new org.netbeans.lib.awtextra.AbsoluteConstraints(427, 11, 77, 27));

        JLPregunta4.setText("Selecciona la respuesta correcta");
        jPanel5.add(JLPregunta4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 49, -1, 25));

        JP1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        JP1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JB2P1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        JB2P1.setText("4");
        JB2P1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB2P1ActionPerformed(evt);
            }
        });
        JP1.add(JB2P1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 100, 80));

        JB3P1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        JB3P1.setText("10");
        JB3P1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB3P1ActionPerformed(evt);
            }
        });
        JP1.add(JB3P1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 100, 80));

        JLN1.setText("jLabel2");
        JP1.add(JLN1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 170, 110));

        JB1P1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        JB1P1.setText("2");
        JB1P1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB1P1ActionPerformed(evt);
            }
        });
        JP1.add(JB1P1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 100, 80));

        jPanel5.add(JP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, -1, 220));

        JP2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        JP2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JB2P2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        JB2P2.setText("10");
        JB2P2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB2P2ActionPerformed(evt);
            }
        });
        JP2.add(JB2P2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 100, 80));

        JB3P2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        JB3P2.setText("6");
        JB3P2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB3P2ActionPerformed(evt);
            }
        });
        JP2.add(JB3P2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 100, 80));

        JB1P2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        JB1P2.setText("8");
        JB1P2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB1P2ActionPerformed(evt);
            }
        });
        JP2.add(JB1P2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 100, 80));

        JLN2.setText("jLabel2");
        JP2.add(JLN2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 170, 110));

        jPanel5.add(JP2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 140, -1, 220));

        JP3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        JP3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JB2P3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        JB2P3.setText("7");
        JB2P3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB2P3ActionPerformed(evt);
            }
        });
        JP3.add(JB2P3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 100, 80));

        JB3P3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        JB3P3.setText("2");
        JB3P3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB3P3ActionPerformed(evt);
            }
        });
        JP3.add(JB3P3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 100, 80));

        JB1P3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        JB1P3.setText("1");
        JB1P3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB1P3ActionPerformed(evt);
            }
        });
        JP3.add(JB1P3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 100, 80));

        JLN3.setText("jLabel2");
        JP3.add(JLN3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 170, 110));

        jPanel5.add(JP3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 430, -1, 220));

        JP4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        JP4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JB2P4.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        JB2P4.setText("5");
        JB2P4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB2P4ActionPerformed(evt);
            }
        });
        JP4.add(JB2P4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 100, 80));

        JB3P4.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        JB3P4.setText("3");
        JB3P4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB3P4ActionPerformed(evt);
            }
        });
        JP4.add(JB3P4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 100, 80));

        JB1P4.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        JB1P4.setText("10");
        JB1P4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB1P4ActionPerformed(evt);
            }
        });
        JP4.add(JB1P4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 100, 80));

        JLN4.setText("jLabel2");
        JP4.add(JLN4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 170, 110));

        jPanel5.add(JP4, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 430, -1, 220));

        jTabbedPane1.addTab("tab4", jPanel5);

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JLPregunta5.setText("Completa utilizando < menor que, > mayor que");
        jPanel6.add(JLPregunta5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 49, -1, 25));

        JLActividad5.setText("Actividad #5");
        jPanel6.add(JLActividad5, new org.netbeans.lib.awtextra.AbsoluteConstraints(427, 11, 77, 27));

        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel8.setText("10");
        jPanel8.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 60, 70));

        jPanel6.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, 140, 120));

        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setText("5");
        jPanel7.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 40, 70));

        jPanel6.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 140, 120));

        CB1.setBackground(new java.awt.Color(255, 255, 0));
        CB1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        CB1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "  ?", "  <", "  >" }));
        CB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CB1ActionPerformed(evt);
            }
        });
        jPanel6.add(CB1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 90, 80));

        jPanel17.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel13.setText("8");
        jPanel17.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 40, 70));

        jPanel6.add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 160, 140, 120));

        CB2.setBackground(new java.awt.Color(0, 102, 255));
        CB2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        CB2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "  ?", "  <", "  >" }));
        CB2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CB2ActionPerformed(evt);
            }
        });
        jPanel6.add(CB2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 190, 90, 80));

        jPanel18.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel14.setText("3");
        jPanel18.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 40, 70));

        jPanel6.add(jPanel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 160, 140, 120));

        jPanel19.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel15.setText("10");
        jPanel19.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 50, 70));

        jPanel6.add(jPanel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 390, 140, 120));

        CB4.setBackground(new java.awt.Color(102, 255, 51));
        CB4.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        CB4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "  ?", "  <", "  >" }));
        CB4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CB4ActionPerformed(evt);
            }
        });
        jPanel6.add(CB4, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 420, 90, 80));

        jPanel20.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel16.setText("6");
        jPanel20.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 40, 70));

        jPanel6.add(jPanel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 390, 140, 120));

        jPanel21.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel17.setText("25");
        jPanel21.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 60, 70));

        jPanel6.add(jPanel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 390, 140, 120));

        CB3.setBackground(new java.awt.Color(255, 0, 102));
        CB3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        CB3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "  ?", "  <", "  >" }));
        CB3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CB3ActionPerformed(evt);
            }
        });
        jPanel6.add(CB3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 420, 90, 80));

        jPanel22.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel18.setText("5");
        jPanel22.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 40, 70));

        jPanel6.add(jPanel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, 140, 120));

        jLabel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel6.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 150, 410, 150));

        jLabel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel6.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 380, 410, 150));

        jLabel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel6.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 410, 150));

        jLabel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel6.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 410, 150));

        jTabbedPane1.addTab("tab5", jPanel6);

        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JLPregunta6.setText("Identifique el tipo de triángulos según corresponda.");
        jPanel9.add(JLPregunta6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 49, -1, 25));

        JLActividad6.setText("Actividad #6");
        jPanel9.add(JLActividad6, new org.netbeans.lib.awtextra.AbsoluteConstraints(427, 11, 77, 27));

        JLTriangulo1.setText("jLabel19");
        jPanel9.add(JLTriangulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 410, 180, 180));

        JLTriangulo2.setText("jLabel19");
        jPanel9.add(JLTriangulo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 140, 180));

        JLTriangulo3.setText("jLabel19");
        jPanel9.add(JLTriangulo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 220, 180));

        JBT1.setText("EQUILÁTERO");
        JBT1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                JBT1MouseDragged(evt);
            }
        });
        JBT1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                JBT1MouseReleased(evt);
            }
        });
        jPanel9.add(JBT1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 90, 130, 40));

        JBT5.setText("ISÓSCELES");
        JBT5.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                JBT5MouseDragged(evt);
            }
        });
        JBT5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                JBT5MouseReleased(evt);
            }
        });
        jPanel9.add(JBT5, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 160, 130, 40));

        JBT2.setText("RECTÁNGULO");
        JBT2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                JBT2MouseDragged(evt);
            }
        });
        JBT2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                JBT2MouseReleased(evt);
            }
        });
        jPanel9.add(JBT2, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 90, 130, 40));

        JBT4.setText("OBTUSÁNGULO");
        JBT4.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                JBT4MouseDragged(evt);
            }
        });
        JBT4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                JBT4MouseReleased(evt);
            }
        });
        jPanel9.add(JBT4, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 220, 130, 40));

        JBT3.setText("ESCALENO");
        JBT3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                JBT3MouseDragged(evt);
            }
        });
        JBT3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                JBT3MouseReleased(evt);
            }
        });
        jPanel9.add(JBT3, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 220, 130, 40));

        jPanel15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel9.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 50, 340, 250));

        JPT3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel9.add(JPT3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 460, 200, 90));

        JPT2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel9.add(JPT2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 200, 200, 90));

        JPT1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel9.add(JPT1, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 460, 200, 90));

        jTabbedPane1.addTab("tab6", jPanel9);

        jPanel1.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, 970, 720));

        jButton1.setText("BOTON VERIFICAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 580, 150, 50));

        JLNota2.setText("jLabel26");
        jPanel1.add(JLNota2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 40, 30));

        JLNota3.setText("jLabel26");
        jPanel1.add(JLNota3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 40, 30));

        JLNota4.setText("jLabel26");
        jPanel1.add(JLNota4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, 40, 30));

        JLNota5.setText("jLabel26");
        jPanel1.add(JLNota5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, 40, 30));

        JLNota6.setText("jLabel26");
        jPanel1.add(JLNota6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 350, 40, 30));

        jButton5.setText("regresar a modulos ");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 640, 160, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 1260, 820));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JL1_2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JL1_2MouseDragged
         
        
        if(evt.getModifiersEx() == MouseEvent.BUTTON1_DOWN_MASK){
            
            jPanel3.setLayout(new BorderLayout());
            JL1_2.setLocation(JL1_2.getLocation().x+ evt.getX() - JL1_2.getWidth()/2 ,
            JL1_2.getLocation().y+ evt.getY() - JL1_2.getHeight());
           
           jLabel3.setText("("+JL1_2.getLocation().x+","+JL1_2.getLocation().y+")") ;
           if(JL1_2.getLocation().x <90 && JL1_2.getLocation().x >40  && JL1_2.getLocation().y >100  &&  JL1_2.getLocation().y <140  ){
              B1 = 1;
               
               //jLabel2.setText("1");
           }else{
               B1=0;
           }
             JL1_2.repaint();
             
           /* if(jLabel10.getLocation() == jLabel20.getLocation() ) {
               jLabel3.setText("correcto");
            }
                //jLabel10.setLocation(evt.getPoint());
                */
            } 
       
    }//GEN-LAST:event_JL1_2MouseDragged

    private void JL1_3MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JL1_3MouseDragged
          if(evt.getModifiersEx() == MouseEvent.BUTTON1_DOWN_MASK){
            
            jPanel3.setLayout(new BorderLayout());
            JL1_3.setLocation(JL1_3.getLocation().x+ evt.getX() - JL1_3.getWidth()/2 ,
            JL1_3.getLocation().y+ evt.getY() - JL1_3.getHeight());
           
          // jLabel3.setText("("+jLabel11.getLocation().x+","+jLabel11.getLocation().y+")") ;
           if(JL1_3.getLocation().x <90 && JL1_3.getLocation().x >40  && JL1_3.getLocation().y >380  &&  JL1_3.getLocation().y <420  ){
               B3 = 1;
             
           }else{
               B3 = 0;
           }
             JL1_3.repaint();
          
            } 
    }//GEN-LAST:event_JL1_3MouseDragged

    private void JL1_2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JL1_2MouseReleased
      if(JL1_2.getLocation().x <0 || JL1_2.getLocation().x >890 ||  JL1_2.getLocation().y <0 ||  JL1_2.getLocation().y >520   ){
          JL1_2.setLocation(550, 290);
      }
                
            
    }//GEN-LAST:event_JL1_2MouseReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String calificaion1 =null;
        String calificaion2 =null;
        String calificaion3 =null;
        String calificaion4 =null;
        String calificaion5 =null;
        String calificaion6 =null;
        //nota actividad 1
       
        notafinal1= A1+A2+A3+A4+A5;
        calificaion1 = Integer.toString(notafinal1);
        JLNota1.setText(calificaion1);
        
        //nota actividad 2
        notafinal2 =B1+B2+B3+B4;
        calificaion2 = Integer.toString(notafinal2);
        JLNota2.setText(calificaion2);
        
        
        //nota actividad 3
        
        notafinal3 =C1+C2+C3+C4;
        calificaion3 = Integer.toString(notafinal3);
        JLNota3.setText(calificaion3);
        
         //nota actividad 4
         
        notafinal4 =D1+D2+D3+D4;
        calificaion4 = Integer.toString(notafinal4);
        JLNota4.setText(calificaion4);
        
        
        //nota actividad 5
         
        notafinal5 =E1+E2+E3+E4;
        calificaion5 = Integer.toString(notafinal5);
        JLNota5.setText(calificaion5);
        
        //nota actividad 6
         
        notafinal6 =F1+F2+F3;
        calificaion6 = Integer.toString(notafinal6);
        JLNota6.setText(calificaion6);
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void JL2_3MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JL2_3MouseDragged
        if(evt.getModifiersEx() == MouseEvent.BUTTON1_DOWN_MASK){
            
            jPanel3.setLayout(new BorderLayout());
            JL2_3.setLocation(JL2_3.getLocation().x+ evt.getX() - JL2_3.getWidth()/2 ,
            JL2_3.getLocation().y+ evt.getY() - JL2_3.getHeight());
           
           
           if(JL2_3.getLocation().x <90 && JL2_3.getLocation().x >40  && JL2_3.getLocation().y >240  &&  JL2_3.getLocation().y <280  ){
              B2 =1;
           }else{
              B2=0;
           }
             JL2_3.repaint();
            
            } 
       
    }//GEN-LAST:event_JL2_3MouseDragged

    private void JL2_4MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JL2_4MouseDragged
       if(evt.getModifiersEx() == MouseEvent.BUTTON1_DOWN_MASK){
            
            jPanel3.setLayout(new BorderLayout());
            JL2_4.setLocation(JL2_4.getLocation().x+ evt.getX() - JL2_4.getWidth()/2 ,
            JL2_4.getLocation().y+ evt.getY() - JL2_4.getHeight());
           
           
           if(JL2_4.getLocation().x <90 && JL2_4.getLocation().x >40  && JL2_4.getLocation().y >520  &&  JL2_4.getLocation().y <560  ){
              B4 = 1;
           }else{
              B4=0;
           }
             JL2_3.repaint();
            
            } 
    }//GEN-LAST:event_JL2_4MouseDragged

    private void JL3_4MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JL3_4MouseDragged
        if(evt.getModifiersEx() == MouseEvent.BUTTON1_DOWN_MASK){
            
            jPanel3.setLayout(new BorderLayout());
            JL3_4.setLocation(JL3_4.getLocation().x+ evt.getX() - JL3_4.getWidth()/2 ,
            JL3_4.getLocation().y+ evt.getY() - JL3_4.getHeight());
           
             JL3_4.repaint();
            
            } 
    }//GEN-LAST:event_JL3_4MouseDragged

    private void JL1_3MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JL1_3MouseReleased
          if(JL1_3.getLocation().x <0 || JL1_3.getLocation().x >890 ||  JL1_3.getLocation().y <0 ||  JL1_3.getLocation().y >600   ){
          JL1_3.setLocation(550, 450);
      }
    }//GEN-LAST:event_JL1_3MouseReleased

    private void JL2_3MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JL2_3MouseReleased
          if(JL2_3.getLocation().x <0 || JL2_3.getLocation().x >890 ||  JL2_3.getLocation().y <0 ||  JL2_3.getLocation().y >600   ){
          JL2_3.setLocation(800, 290);
      }
    }//GEN-LAST:event_JL2_3MouseReleased

    private void JL2_4MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JL2_4MouseReleased
         if(JL2_4.getLocation().x <0 || JL2_4.getLocation().x >890 ||  JL2_4.getLocation().y <0 ||  JL2_4.getLocation().y >600   ){
          JL2_4.setLocation(800, 450);
      }
    }//GEN-LAST:event_JL2_4MouseReleased

    private void JL3_4MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JL3_4MouseReleased
         if(JL3_4.getLocation().x <0 || JL3_4.getLocation().x >890 ||  JL3_4.getLocation().y <0 ||  JL3_4.getLocation().y >600   ){
          JL3_4.setLocation(670, 380);
      }
    }//GEN-LAST:event_JL3_4MouseReleased

    private void JB1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JB1MouseDragged
       
                    
    }//GEN-LAST:event_JB1MouseDragged

    private void JPN3MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPN3MouseDragged
        if(evt.getModifiersEx() == MouseEvent.BUTTON1_DOWN_MASK){
            
            jPanel2.setLayout(new BorderLayout());
             JPN3.setLocation( JPN3.getLocation().x+ evt.getX() -  JPN3.getWidth()/2 ,
             JPN3.getLocation().y+ evt.getY() -  JPN3.getHeight());
             jLabel3.setText("("+JPN3.getLocation().x+","+JPN3.getLocation().y+")") ;
             if (JPN3.getLocation().x <301 && JPN3.getLocation().x >266  && JPN3.getLocation().y >334  &&  JPN3.getLocation().y <354  ){
              
              A1=1;
           }else{
              A1=0;
             } 
         
              JPN3.repaint();
            
            } 
    }//GEN-LAST:event_JPN3MouseDragged

    private void JPN4MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPN4MouseDragged
        if(evt.getModifiersEx() == MouseEvent.BUTTON1_DOWN_MASK){
            
            jPanel2.setLayout(new BorderLayout());
             JPN4.setLocation( JPN4.getLocation().x+ evt.getX() -  JPN4.getWidth()/2 ,
             JPN4.getLocation().y+ evt.getY() -  JPN4.getHeight());
             
             if (JPN4.getLocation().x <469 && JPN4.getLocation().x >432  && JPN4.getLocation().y >464  &&  JPN4.getLocation().y <482  ){
              
              A2=1;
           }else{
              A2=0;
             } 
         
              JPN4.repaint();
            
            } 
    }//GEN-LAST:event_JPN4MouseDragged

    private void JPN5MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPN5MouseDragged
        if(evt.getModifiersEx() == MouseEvent.BUTTON1_DOWN_MASK){
            
            jPanel2.setLayout(new BorderLayout());
             JPN5.setLocation( JPN5.getLocation().x+ evt.getX() -  JPN5.getWidth()/2 ,
             JPN5.getLocation().y+ evt.getY() -  JPN5.getHeight());
            
             if (JPN5.getLocation().x <305 && JPN5.getLocation().x >270  && JPN5.getLocation().y >85  &&  JPN5.getLocation().y <104  ){
              
              A3=1;
           }else{
              A3=0;
             } 
         
              JPN5.repaint();
            
            } 
    }//GEN-LAST:event_JPN5MouseDragged

    private void JPN6MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPN6MouseDragged
        if(evt.getModifiersEx() == MouseEvent.BUTTON1_DOWN_MASK){
            
            jPanel2.setLayout(new BorderLayout());
             JPN6.setLocation( JPN6.getLocation().x+ evt.getX() -  JPN6.getWidth()/2 ,
             JPN6.getLocation().y+ evt.getY() -  JPN6.getHeight());
             
              JPN6.repaint();
            
            } 
    }//GEN-LAST:event_JPN6MouseDragged

    private void JPN2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPN2MouseDragged
       if(evt.getModifiersEx() == MouseEvent.BUTTON1_DOWN_MASK){
            
            jPanel2.setLayout(new BorderLayout());
             JPN2.setLocation( JPN2.getLocation().x+ evt.getX() -  JPN2.getWidth()/2 ,
             JPN2.getLocation().y+ evt.getY() -  JPN2.getHeight());
             
             if (JPN2.getLocation().x <304 && JPN2.getLocation().x >267  && JPN2.getLocation().y >586  &&  JPN2.getLocation().y <605  ){
              
              A4=1;
           }else{
              A4=0;
             } 
         
              JPN2.repaint();
            
            } 
    }//GEN-LAST:event_JPN2MouseDragged

    private void JPN12MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPN12MouseDragged
        if(evt.getModifiersEx() == MouseEvent.BUTTON1_DOWN_MASK){
            
            jPanel2.setLayout(new BorderLayout());
             JPN12.setLocation( JPN12.getLocation().x+ evt.getX() -  JPN12.getWidth()/2 ,
             JPN12.getLocation().y+ evt.getY() -  JPN12.getHeight());
            
             if (JPN12.getLocation().x <632 && JPN12.getLocation().x >594  && JPN12.getLocation().y >336  &&  JPN12.getLocation().y <357  ){
              
              A5=1;
           }else{
              A5=0;
             } 
         
              JPN12.repaint();
            
            } 
    }//GEN-LAST:event_JPN12MouseDragged

    private void JPN3MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPN3MouseReleased
        if(JPN3.getLocation().x <0 || JPN3.getLocation().x >890 ||  JPN3.getLocation().y <0 ||  JPN3.getLocation().y >600   ){
          JPN3.setLocation(722, 100);
      }       
    }//GEN-LAST:event_JPN3MouseReleased

    private void JPN4MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPN4MouseReleased
        if(JPN4.getLocation().x <0 || JPN4.getLocation().x >890 ||  JPN4.getLocation().y <0 ||  JPN4.getLocation().y >600   ){
          JPN4.setLocation(790, 100);
      }      
    }//GEN-LAST:event_JPN4MouseReleased

    private void JPN5MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPN5MouseReleased
      if(JPN5.getLocation().x <0 || JPN5.getLocation().x >890 ||  JPN5.getLocation().y <0 ||  JPN5.getLocation().y >600   ){
          JPN5.setLocation(722, 160);
      }     
    }//GEN-LAST:event_JPN5MouseReleased

    private void JPN6MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPN6MouseReleased
        if(JPN6.getLocation().x <0 || JPN6.getLocation().x >890 ||  JPN6.getLocation().y <0 ||  JPN6.getLocation().y >600   ){
          JPN6.setLocation(790, 160);
      }  
    }//GEN-LAST:event_JPN6MouseReleased

    private void JPN2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPN2MouseReleased
        if(JPN2.getLocation().x <0 || JPN2.getLocation().x >890 ||  JPN2.getLocation().y <0 ||  JPN2.getLocation().y >600   ){
          JPN2.setLocation(722, 220);
      }  
    }//GEN-LAST:event_JPN2MouseReleased

    private void JPN12MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPN12MouseReleased
       if(JPN12.getLocation().x <0 || JPN12.getLocation().x >890 ||  JPN12.getLocation().y <0 ||  JPN12.getLocation().y >600   ){
          JPN12.setLocation(790, 220);
       }
    }//GEN-LAST:event_JPN12MouseReleased

    private void jLabel31MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel31MouseDragged
        if(evt.getModifiersEx() == MouseEvent.BUTTON1_DOWN_MASK){
            
            jPanel4.setLayout(new BorderLayout());
            jLabel31.setLocation(jLabel31.getLocation().x+ evt.getX() - jLabel31.getWidth()/2 ,
            jLabel31.getLocation().y+ evt.getY() - jLabel31.getHeight());
           
          jLabel3.setText("("+jLabel31.getLocation().x+","+jLabel31.getLocation().y+")") ;
           if(jLabel31.getLocation().x <440 && jLabel31.getLocation().x >330  && jLabel31.getLocation().y >240  &&  jLabel31.getLocation().y <290  ){
               C1 = 1;
             
           }else{
               C1 = 0;
           }
             JL1_3.repaint();
          
            } 
    }//GEN-LAST:event_jLabel31MouseDragged

    private void jLabel30MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel30MouseDragged
       if(evt.getModifiersEx() == MouseEvent.BUTTON1_DOWN_MASK){
            
            jPanel4.setLayout(new BorderLayout());
            jLabel30.setLocation(jLabel30.getLocation().x+ evt.getX() - jLabel30.getWidth()/2 ,
            jLabel30.getLocation().y+ evt.getY() - jLabel30.getHeight());
           
         
           if(jLabel30.getLocation().x <440 && jLabel30.getLocation().x >330  && jLabel30.getLocation().y >510  &&  jLabel30.getLocation().y <560  ){
               C2 = 1;
             
           }else{
               C2 = 0;
           }
             jLabel30.repaint();
          
            } 
    }//GEN-LAST:event_jLabel30MouseDragged

    private void jLabel26MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel26MouseDragged
        if(evt.getModifiersEx() == MouseEvent.BUTTON1_DOWN_MASK){
            
            jPanel4.setLayout(new BorderLayout());
            jLabel26.setLocation(jLabel26.getLocation().x+ evt.getX() - jLabel26.getWidth()/2 ,
            jLabel26.getLocation().y+ evt.getY() - jLabel26.getHeight());
           
          
           if(jLabel26.getLocation().x <440 && jLabel26.getLocation().x >330  && jLabel26.getLocation().y >380  &&  jLabel26.getLocation().y <430  ){
               C3 = 1;
             
           }else{
               C3 = 0;
           }
             jLabel26.repaint();
          
            } 
    }//GEN-LAST:event_jLabel26MouseDragged

    private void jLabel28MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel28MouseDragged
        if(evt.getModifiersEx() == MouseEvent.BUTTON1_DOWN_MASK){
            
            jPanel4.setLayout(new BorderLayout());
            jLabel28.setLocation(jLabel28.getLocation().x+ evt.getX() - jLabel28.getWidth()/2 ,
            jLabel28.getLocation().y+ evt.getY() - jLabel28.getHeight());
           
             jLabel28.repaint();
          
            } 
    }//GEN-LAST:event_jLabel28MouseDragged

    private void jLabel27MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel27MouseDragged
        if(evt.getModifiersEx() == MouseEvent.BUTTON1_DOWN_MASK){
            
            jPanel4.setLayout(new BorderLayout());
            jLabel27.setLocation(jLabel27.getLocation().x+ evt.getX() - jLabel27.getWidth()/2 ,
            jLabel27.getLocation().y+ evt.getY() - jLabel27.getHeight());
           
          
           if(jLabel27.getLocation().x <400 && jLabel27.getLocation().x >330  && jLabel27.getLocation().y >100  &&  jLabel27.getLocation().y <150  ){
               C4 = 1;
             
           }else{
               C4 = 0;
           }
             jLabel27.repaint();
          
            } 
    }//GEN-LAST:event_jLabel27MouseDragged

    private void jLabel31MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel31MouseReleased
        if(jLabel31.getLocation().x <0 || jLabel31.getLocation().x >890 ||  jLabel31.getLocation().y <0 ||  jLabel31.getLocation().y >600   ){
          jLabel31.setLocation(660, 150);
      }
          
    }//GEN-LAST:event_jLabel31MouseReleased

    private void jLabel30MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel30MouseReleased
         if(jLabel30.getLocation().x <0 || jLabel30.getLocation().x >890 ||  jLabel30.getLocation().y <0 ||  jLabel30.getLocation().y >600   ){
          jLabel30.setLocation(660, 250);
      }
          
    }//GEN-LAST:event_jLabel30MouseReleased

    private void jLabel26MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel26MouseReleased
        if(jLabel26.getLocation().x <0 || jLabel26.getLocation().x >890 ||  jLabel26.getLocation().y <0 ||  jLabel26.getLocation().y >600   ){
          jLabel26.setLocation(660, 350);
      }
          
    }//GEN-LAST:event_jLabel26MouseReleased

    private void jLabel28MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel28MouseReleased
        if(jLabel28.getLocation().x <0 || jLabel28.getLocation().x >890 ||  jLabel28.getLocation().y <0 ||  jLabel28.getLocation().y >600   ){
          jLabel28.setLocation(660, 460);
      }
          
    }//GEN-LAST:event_jLabel28MouseReleased

    private void jLabel27MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel27MouseReleased
         if(jLabel27.getLocation().x <0 || jLabel27.getLocation().x >890 ||  jLabel27.getLocation().y <0 ||  jLabel27.getLocation().y >600   ){
          jLabel27.setLocation(660, 550);
      }
          
    }//GEN-LAST:event_jLabel27MouseReleased

    private void JB1P1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB1P1ActionPerformed
        
             JB1P1.setBackground(Color.green);
             JB2P1.setBackground(Color.white);
             JB3P1.setBackground(Color.white);
             D1=0;
       
    }//GEN-LAST:event_JB1P1ActionPerformed

    private void JB2P1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB2P1ActionPerformed
             JB2P1.setBackground(Color.green);
             JB1P1.setBackground(Color.white);
             JB3P1.setBackground(Color.white);
             D1=1;
    }//GEN-LAST:event_JB2P1ActionPerformed

    private void JB3P1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB3P1ActionPerformed
             JB3P1.setBackground(Color.green);
             JB2P1.setBackground(Color.white);
             JB1P1.setBackground(Color.white);
             D1=0;
    }//GEN-LAST:event_JB3P1ActionPerformed

    private void JB1P2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB1P2ActionPerformed
             JB1P2.setBackground(Color.green);
             JB2P2.setBackground(Color.white);
             JB3P2.setBackground(Color.white);
             D2=1;
    }//GEN-LAST:event_JB1P2ActionPerformed

    private void JB2P2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB2P2ActionPerformed
             JB2P2.setBackground(Color.green);
             JB1P2.setBackground(Color.white);
             JB3P2.setBackground(Color.white);
             D2=0;
    }//GEN-LAST:event_JB2P2ActionPerformed

    private void JB3P2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB3P2ActionPerformed
             JB3P2.setBackground(Color.green);
             JB2P2.setBackground(Color.white);
             JB1P2.setBackground(Color.white);
             D2=0;
    }//GEN-LAST:event_JB3P2ActionPerformed

    private void JB1P3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB1P3ActionPerformed
             JB1P3.setBackground(Color.green);
             JB2P3.setBackground(Color.white);
             JB3P3.setBackground(Color.white);
             D3=0;
    }//GEN-LAST:event_JB1P3ActionPerformed

    private void JB2P3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB2P3ActionPerformed
             JB2P3.setBackground(Color.green);
             JB1P3.setBackground(Color.white);
             JB3P3.setBackground(Color.white);
             D3=0;
    }//GEN-LAST:event_JB2P3ActionPerformed

    private void JB3P3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB3P3ActionPerformed
             JB3P3.setBackground(Color.green);
             JB2P3.setBackground(Color.white);
             JB1P3.setBackground(Color.white);
             D3=1;
    }//GEN-LAST:event_JB3P3ActionPerformed

    private void JB1P4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB1P4ActionPerformed
             JB1P4.setBackground(Color.green);
             JB2P4.setBackground(Color.white);
             JB3P4.setBackground(Color.white);
             D4=0;
    }//GEN-LAST:event_JB1P4ActionPerformed

    private void JB2P4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB2P4ActionPerformed
             JB2P4.setBackground(Color.green);
             JB3P4.setBackground(Color.white);
             JB1P4.setBackground(Color.white);
             D4=1;
    }//GEN-LAST:event_JB2P4ActionPerformed

    private void JB3P4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB3P4ActionPerformed
             JB3P4.setBackground(Color.green);
             JB2P4.setBackground(Color.white);
             JB1P4.setBackground(Color.white);
             D4=0;
    }//GEN-LAST:event_JB3P4ActionPerformed

    private void CB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CB1ActionPerformed
       if(CB1.getSelectedItem().equals("  <")){
            E1=1;
        }else{
            E1=0;
        }
    }//GEN-LAST:event_CB1ActionPerformed

    private void CB2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CB2ActionPerformed
        if(CB2.getSelectedItem().equals("  >")){
            E2=1;
        }else{
            E2=0;
        }
    }//GEN-LAST:event_CB2ActionPerformed

    private void CB3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CB3ActionPerformed
        if(CB3.getSelectedItem().equals("  <")){
            E3=1;
        }else{
            E3=0;
        }
    }//GEN-LAST:event_CB3ActionPerformed

    private void CB4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CB4ActionPerformed
        if(CB2.getSelectedItem().equals("  >")){
            E4=1;
        }else{
            E4=0;
        }
    }//GEN-LAST:event_CB4ActionPerformed

    private void JBT1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBT1MouseDragged
if(evt.getModifiersEx() == MouseEvent.BUTTON1_DOWN_MASK){
            
            jPanel9.setLayout(new BorderLayout());
            JBT1.setLocation(JBT1.getLocation().x+ evt.getX() - JBT1.getWidth()/2 ,
            JBT1.getLocation().y+ evt.getY() - JBT1.getHeight());
           
          jLabel3.setText("("+JBT1.getLocation().x+","+JBT1.getLocation().y+")") ;
           if(JBT1.getLocation().x <810 && JBT1.getLocation().x >740  && JBT1.getLocation().y >460  &&  JBT1.getLocation().y <510  ){
              F1 = 1;
             
           }else{
              F1 = 0;
           }
             JBT1.repaint();
          
            }         
    }//GEN-LAST:event_JBT1MouseDragged

    private void JBT5MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBT5MouseDragged
        jPanel9.setLayout(new BorderLayout());
            JBT5.setLocation(JBT5.getLocation().x+ evt.getX() - JBT5.getWidth()/2 ,
            JBT5.getLocation().y+ evt.getY() - JBT5.getHeight());
    
           if(JBT5.getLocation().x <342 && JBT5.getLocation().x >270  && JBT5.getLocation().y >200  &&  JBT5.getLocation().y <250  ){
               F2 = 1;
             
           }else{
               F2 = 0;
           }
             JBT5.repaint();
    }//GEN-LAST:event_JBT5MouseDragged

    private void JBT2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBT2MouseDragged
       if(evt.getModifiersEx() == MouseEvent.BUTTON1_DOWN_MASK){
            
            jPanel9.setLayout(new BorderLayout());
            JBT2.setLocation(JBT2.getLocation().x+ evt.getX() - JBT2.getWidth()/2 ,
            JBT2.getLocation().y+ evt.getY() - JBT2.getHeight());
           
             JBT2.repaint();
       }   
    }//GEN-LAST:event_JBT2MouseDragged

    private void JBT4MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBT4MouseDragged
        if(evt.getModifiersEx() == MouseEvent.BUTTON1_DOWN_MASK){
            
            jPanel9.setLayout(new BorderLayout());
            JBT4.setLocation(JBT4.getLocation().x+ evt.getX() - JBT4.getWidth()/2 ,
            JBT4.getLocation().y+ evt.getY() - JBT4.getHeight());
           
             JBT4.repaint();
          
            }        
    }//GEN-LAST:event_JBT4MouseDragged

    private void JBT3MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBT3MouseDragged
        if(evt.getModifiersEx() == MouseEvent.BUTTON1_DOWN_MASK){
            
            jPanel9.setLayout(new BorderLayout());
            JBT3.setLocation(JBT3.getLocation().x+ evt.getX() - JBT3.getWidth()/2 ,
            JBT3.getLocation().y+ evt.getY() - JBT3.getHeight());
           
           if(JBT3.getLocation().x <342 && JBT3.getLocation().x >270  && JBT3.getLocation().y >457  &&  JBT3.getLocation().y <513  ){
              F3 = 1;
             
           }else{
              F3 = 0;
           }
             JBT3.repaint();
          
            }        
    }//GEN-LAST:event_JBT3MouseDragged

    private void JBT1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBT1MouseReleased
        if(JBT1.getLocation().x <0 || JBT1.getLocation().x >890 ||  JBT1.getLocation().y <0 ||  JBT1.getLocation().y >600   ){
          JBT1.setLocation(610, 90);
      }
    }//GEN-LAST:event_JBT1MouseReleased

    private void JBT2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBT2MouseReleased
       if(JBT2.getLocation().x <0 || JBT2.getLocation().x >890 ||  JBT2.getLocation().y <0 ||  JBT2.getLocation().y >600   ){
          JBT2.setLocation(800, 90);
      }
    }//GEN-LAST:event_JBT2MouseReleased

    private void JBT5MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBT5MouseReleased
       if(JBT5.getLocation().x <0 || JBT5.getLocation().x >890 ||  JBT5.getLocation().y <0 ||  JBT5.getLocation().y >600   ){
          JBT5.setLocation(710, 160);
      }
    }//GEN-LAST:event_JBT5MouseReleased

    private void JBT3MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBT3MouseReleased
        if(JBT3.getLocation().x <0 || JBT3.getLocation().x >890 ||  JBT3.getLocation().y <0 ||  JBT3.getLocation().y >600   ){
          JBT3.setLocation(610, 220);
      }
    }//GEN-LAST:event_JBT3MouseReleased

    private void JBT4MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBT4MouseReleased
        if(JBT4.getLocation().x <0 || JBT4.getLocation().x >890 ||  JBT4.getLocation().y <0 ||  JBT4.getLocation().y >600   ){
          JBT4.setLocation(800, 220);
      }
    }//GEN-LAST:event_JBT4MouseReleased

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        FrmModulos v = new FrmModulos();
        v.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMatematicas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMatematicas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMatematicas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMatematicas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMatematicas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CB1;
    private javax.swing.JComboBox<String> CB2;
    private javax.swing.JComboBox<String> CB3;
    private javax.swing.JComboBox<String> CB4;
    private javax.swing.JButton JB1;
    private javax.swing.JButton JB10;
    private javax.swing.JButton JB1P1;
    private javax.swing.JButton JB1P2;
    private javax.swing.JButton JB1P3;
    private javax.swing.JButton JB1P4;
    private javax.swing.JButton JB2;
    private javax.swing.JButton JB2P1;
    private javax.swing.JButton JB2P2;
    private javax.swing.JButton JB2P3;
    private javax.swing.JButton JB2P4;
    private javax.swing.JButton JB3;
    private javax.swing.JButton JB3P1;
    private javax.swing.JButton JB3P2;
    private javax.swing.JButton JB3P3;
    private javax.swing.JButton JB3P4;
    private javax.swing.JButton JB4;
    private javax.swing.JButton JB5;
    private javax.swing.JButton JB6;
    private javax.swing.JButton JB7;
    private javax.swing.JButton JB8;
    private javax.swing.JButton JB9;
    private javax.swing.JButton JBT1;
    private javax.swing.JButton JBT2;
    private javax.swing.JButton JBT3;
    private javax.swing.JButton JBT4;
    private javax.swing.JButton JBT5;
    private javax.swing.JLabel JL;
    private javax.swing.JLabel JL1;
    private javax.swing.JLabel JL1_2;
    private javax.swing.JLabel JL1_3;
    private javax.swing.JLabel JL2;
    private javax.swing.JLabel JL2_3;
    private javax.swing.JLabel JL2_4;
    private javax.swing.JLabel JL3;
    private javax.swing.JLabel JL3_4;
    private javax.swing.JLabel JL4;
    private javax.swing.JLabel JL5;
    private javax.swing.JLabel JLActividad1;
    private javax.swing.JLabel JLActividad2;
    private javax.swing.JLabel JLActividad3;
    private javax.swing.JLabel JLActividad4;
    private javax.swing.JLabel JLActividad5;
    private javax.swing.JLabel JLActividad6;
    private javax.swing.JLabel JLCono;
    private javax.swing.JLabel JLImagen1;
    private javax.swing.JLabel JLLeche;
    private javax.swing.JLabel JLN1;
    private javax.swing.JLabel JLN2;
    private javax.swing.JLabel JLN3;
    private javax.swing.JLabel JLN4;
    private javax.swing.JLabel JLNaranja;
    private javax.swing.JLabel JLNota1;
    private javax.swing.JLabel JLNota2;
    private javax.swing.JLabel JLNota3;
    private javax.swing.JLabel JLNota4;
    private javax.swing.JLabel JLNota5;
    private javax.swing.JLabel JLNota6;
    private javax.swing.JLabel JLPiramide;
    private javax.swing.JLabel JLPregunta1;
    private javax.swing.JLabel JLPregunta2;
    private javax.swing.JLabel JLPregunta3;
    private javax.swing.JLabel JLPregunta4;
    private javax.swing.JLabel JLPregunta5;
    private javax.swing.JLabel JLPregunta6;
    private javax.swing.JLabel JLTriangulo1;
    private javax.swing.JLabel JLTriangulo2;
    private javax.swing.JLabel JLTriangulo3;
    private javax.swing.JPanel JP1;
    private javax.swing.JPanel JP2;
    private javax.swing.JPanel JP3;
    private javax.swing.JPanel JP4;
    private javax.swing.JPanel JPN12;
    private javax.swing.JPanel JPN2;
    private javax.swing.JPanel JPN3;
    private javax.swing.JPanel JPN4;
    private javax.swing.JPanel JPN5;
    private javax.swing.JPanel JPN6;
    private javax.swing.JPanel JPT1;
    private javax.swing.JPanel JPT2;
    private javax.swing.JPanel JPT3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables

}
