/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examenes;

import MetodosSQL.MetodosSQL;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author javie
 */
public class FrmRegistroUsuarios extends javax.swing.JFrame {

     
    /**
     * Creates new form FrmRegistroUsuario
     */
    public FrmRegistroUsuarios(java.awt.Frame parent, boolean modal) {
       // super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        JlCorreo.setVisible(false);
        BtGuardar.setEnabled(false);
        rsscalelabel.RSScaleLabel.setScaleLabel(JLImagen,"src/imagenes/mando.jpg");
       // BtRegresar.setIcon(setIcon("/Imagenes/regresar.png", BtRegresar));
        //rsscalelabel.RSScaleLabel.setScaleLabel(jLabel1,"src/imagenes/U.png");
        
    }
        MetodosSQL metodos = new MetodosSQL(); 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    
    
   
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        BtGuardar = new javax.swing.JButton();
        BtRegresar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtApellidos = new javax.swing.JTextField();
        txtNombres = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        JlCorreo = new javax.swing.JLabel();
        JLImagen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(249, 239, 36));
        jPanel2.setForeground(new java.awt.Color(0, 51, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtGuardar.setBackground(new java.awt.Color(0, 204, 255));
        BtGuardar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BtGuardar.setText("Guardar y Continuar");
        BtGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtGuardarActionPerformed(evt);
            }
        });
        jPanel2.add(BtGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, 150, 31));

        BtRegresar.setBackground(new java.awt.Color(0, 204, 255));
        BtRegresar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BtRegresar.setText("Regresar");
        BtRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtRegresarActionPerformed(evt);
            }
        });
        jPanel2.add(BtRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 370, 88, 31));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Apellidos");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, -1, -1));

        txtApellidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidosActionPerformed(evt);
            }
        });
        txtApellidos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApellidosKeyTyped(evt);
            }
        });
        jPanel2.add(txtApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, 160, 25));

        txtNombres.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombresKeyTyped(evt);
            }
        });
        jPanel2.add(txtNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 160, 25));

        txtCorreo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCorreoFocusLost(evt);
            }
        });
        jPanel2.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 160, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Correo");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Nombres");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, -1, -1));

        jLabel7.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel7.setText("Registrate para empezar!");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 220, -1));

        JlCorreo.setForeground(new java.awt.Color(255, 0, 0));
        JlCorreo.setText("correo invalido ");
        jPanel2.add(JlCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, 100, 20));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 420));
        getContentPane().add(JLImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 0, 630, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCorreoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCorreoFocusLost
        if(metodos.verificar_Email(txtCorreo.getText())){

            JlCorreo.setVisible(false);
            BtGuardar.setEnabled(true);

        }else{
            JlCorreo.setVisible(true);
            BtGuardar.setEnabled(false);
        }

    }//GEN-LAST:event_txtCorreoFocusLost

    private void txtApellidosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidosKeyTyped
        char c = evt.getKeyChar();

        if((c<'a'|| c> 'z') && (c<'A' )| c>'Z')evt.consume();
        //Toolkit.getDefaultToolkit().beep();
    }//GEN-LAST:event_txtApellidosKeyTyped

    private void txtApellidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidosActionPerformed

    private void BtRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtRegresarActionPerformed
        FrmLogin ventana =  new FrmLogin();
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtRegresarActionPerformed

    private void txtNombresKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombresKeyTyped
        char c = evt.getKeyChar();

        if((c<'a'|| c> 'z') && (c<'A' )| c>'Z')evt.consume();
        //Toolkit.getDefaultToolkit().beep();
    }//GEN-LAST:event_txtNombresKeyTyped

    private void BtGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtGuardarActionPerformed

       //boolean nombre = metodos.ValidarLetras(txtNombres.getText());
       // boolean apellido = metodos.ValidarLetras(txtApellidos.getText());

        if (txtNombres.getText().equals("") || txtApellidos.getText().equals("") || txtCorreo.getText().equals("") ){
            JOptionPane.showMessageDialog(null, "Faltan campos por llenar ");
        }else{
            //if (metodos.ValidarUsuarioRepetido(txtUsuario.getText())==0 ){

                metodos.guardar(txtNombres.getText(),txtApellidos.getText(), txtCorreo.getText());
                JOptionPane.showMessageDialog(null, "guardado ");

            } /*else{
                JOptionPane.showMessageDialog(null, "el usuario ya existe ");
            }*/
       
        FrmModulos ventana = new FrmModulos();
       // ventana.LbUser.setText(Buscar_Nombre);
       
       
       
       ventana.setVisible(true);
       this.dispose();

    }//GEN-LAST:event_BtGuardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmRegistroUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmRegistroUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmRegistroUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmRegistroUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrmRegistroUsuarios dialog = new FrmRegistroUsuarios(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
    public Icon setIcon(String url, JButton boton){
    
        ImageIcon icon = new ImageIcon( getClass().getResource(url));
        
        int ancho = boton.getWidth();
        int alto = boton.getHeight();
        
        ImageIcon icono = new ImageIcon(icon.getImage().getScaledInstance(ancho,alto,Image.SCALE_DEFAULT));
        
        return icono;
      
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtGuardar;
    private javax.swing.JButton BtRegresar;
    private javax.swing.JLabel JLImagen;
    private javax.swing.JLabel JlCorreo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtNombres;
    // End of variables declaration//GEN-END:variables
    





}