/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package examenes;

import MetodosSQL.MetodosSQL;
import static examenes.FrmModulos.Barra;
import java.awt.BorderLayout;
import java.awt.Color;
import static java.awt.Color.green;
import java.awt.event.MouseEvent;
import java.math.BigDecimal;
import java.math.RoundingMode;

/**
 *
 * @author javie
 */
public class FrmSociales extends javax.swing.JFrame {

    /** Creates new form FrmLenguaje */
    public FrmSociales() {
        
        initComponents();
        setLocationRelativeTo(null);
        this.setResizable(false);
        rsscalelabel.RSScaleLabel.setScaleLabel(JLImagen1,"src/imagenes/ImagenSociales1.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(JLImagenNorte,"src/imagenes/sol.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(JLImagenSur,"src/imagenes/pelota.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(JLImagenEste,"src/imagenes/perro.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(JLImagenOeste,"src/imagenes/sonbrilla.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(JLImagenLuna,"src/imagenes/luna.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(JLImagenSol,"src/imagenes/soll.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(JLImagenTierra,"src/imagenes/tierra.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(JLEcuador,"src/imagenes/ecuadorr.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(JLFamilia,"src/imagenes/familia.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(JLRespeto,"src/imagenes/respeto.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(JLEducacion,"src/imagenes/estudio.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(JLSalud,"src/imagenes/salud.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(JLCumplir,"src/imagenes/tareas.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(JLCuidar,"src/imagenes/cuidarp.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(JLbandera,"src/imagenes/bandera.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(JLMachu,"src/imagenes/Machu Picchu.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(JLFlora,"src/imagenes/flora y fauna.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(JLEscudo,"src/imagenes/escudo.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(JLCostumbre,"src/imagenes/costumbre.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(JLCostitucion,"src/imagenes/constitucion.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(JLI1,"src/imagenes/apagar luces.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(JLI2,"src/imagenes/basura.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(JLI3,"src/imagenes/talar arboles.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(JLI4,"src/imagenes/sembrar.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(JLI5,"src/imagenes/reciclar.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(JLPiramide,"src/imagenes/piramide.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(JLLimitacion,"src/imagenes/ecuadorlimitacion.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(jLabel1,"src/imagenes/celeste.jpg");
        
        JBFinalizar.setVisible(false);
        JBFinalizar.setEnabled(false);
        jTabbedPane1.setEnabledAt(0, false);
        jTabbedPane1.setEnabledAt(1, false);
        jTabbedPane1.setEnabledAt(2, false);
        jTabbedPane1.setEnabledAt(3, false);
        jTabbedPane1.setEnabledAt(4, false);
        jTabbedPane1.setEnabledAt(5, false);
        jTabbedPane1.setEnabledAt(6, false);
        jTabbedPane1.setEnabledAt(7, false);
        jTabbedPane1.setEnabledAt(8, false);    
        
    }
    MetodosSQL metodos = new MetodosSQL();
    int contador =0;
    int s1 =0;
    double SumaTotal =0; 
    // nota 1
    int notafinal1 =0;
    int A1=0;
    int A2=0;
    int A3=0;
    int A4=0;
    
    //nota 2
    int notafinal2=0;
    int B1=0;
    int B2=0;
    int B3=0;
    
    //nota 3
    int notafinal3=0;
    int C1=0;
    int C2=0;
    int C3=0;
    int C4=0;
    
     //nota 4
    int notafinal4=0;
    int D1=0;
    int D2=0;
    int D3=0;
    int D4=0;
    int D5=0;
    int D6=0;
    
    int notafinal5=0;
    int E1=0;
    int E2=0;
    int E3=0;
    int E4=0;
    
     //nota 6
    int notafinal6=0;
    int F1=0;
    int F2=0;
    int F3=0;
    int F4=0;
    int F5=0;
    
     //nota 7
    int notafinal7=0;
    int G1=0;
    int G2=0;
    int G3=0;
    int G4=0;
    int G5=0;
    
     //nota 8
    int notafinal8=0;
    int H1=0;
    int H2=0;
    int H3=0;
    
    
        
        

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel15 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        JLPregunta1 = new javax.swing.JLabel();
        JLActividad1 = new javax.swing.JLabel();
        JLImagen1 = new javax.swing.JLabel();
        JLImagenNorte = new javax.swing.JLabel();
        JLImagenEste = new javax.swing.JLabel();
        JLImagenSur = new javax.swing.JLabel();
        JLImagenOeste = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        JPSur = new javax.swing.JPanel();
        JPOeste = new javax.swing.JPanel();
        JPEste = new javax.swing.JPanel();
        JPNorte = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        JLPregunta2 = new javax.swing.JLabel();
        JLActividad2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        JLImagenLuna = new javax.swing.JLabel();
        JLImagenTierra = new javax.swing.JLabel();
        JLImagenSol = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        JBPlaneta = new javax.swing.JButton();
        JBSatelite = new javax.swing.JButton();
        JBEstrella = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        JLActividad3 = new javax.swing.JLabel();
        JLPregunta3 = new javax.swing.JLabel();
        JCBEsmeraldas = new javax.swing.JComboBox<>();
        JCBManabi = new javax.swing.JComboBox<>();
        JCBEloro = new javax.swing.JComboBox<>();
        JCBGuayas = new javax.swing.JComboBox<>();
        JLEcuador = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        JLActividad4 = new javax.swing.JLabel();
        JLPregunta4 = new javax.swing.JLabel();
        JPEducacion = new javax.swing.JPanel();
        JLEducacion = new javax.swing.JLabel();
        JLTexto1 = new javax.swing.JLabel();
        JPRespeto = new javax.swing.JPanel();
        JLRespeto = new javax.swing.JLabel();
        JLTexto2 = new javax.swing.JLabel();
        JPTareas = new javax.swing.JPanel();
        JLCumplir = new javax.swing.JLabel();
        JLTexto3 = new javax.swing.JLabel();
        JPCuidar = new javax.swing.JPanel();
        JLCuidar = new javax.swing.JLabel();
        JLTexto4 = new javax.swing.JLabel();
        JPFamilia = new javax.swing.JPanel();
        JLFamilia = new javax.swing.JLabel();
        JLTexto5 = new javax.swing.JLabel();
        JPSalud = new javax.swing.JPanel();
        JLSalud = new javax.swing.JLabel();
        JLTexto7 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        JPE = new javax.swing.JPanel();
        JLbandera = new javax.swing.JLabel();
        JPM = new javax.swing.JPanel();
        JLMachu = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        JLPregunta5 = new javax.swing.JLabel();
        JLActividad5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        JPE1 = new javax.swing.JPanel();
        JLFlora = new javax.swing.JLabel();
        JPM1 = new javax.swing.JPanel();
        JLEscudo = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        JPE2 = new javax.swing.JPanel();
        JLCostumbre = new javax.swing.JLabel();
        JPM2 = new javax.swing.JPanel();
        JLCostitucion = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        JLPregunta6 = new javax.swing.JLabel();
        JLActividad6 = new javax.swing.JLabel();
        JPI5 = new javax.swing.JPanel();
        JLI5 = new javax.swing.JLabel();
        JPI1 = new javax.swing.JPanel();
        JLI1 = new javax.swing.JLabel();
        JPI2 = new javax.swing.JPanel();
        JLI2 = new javax.swing.JLabel();
        JPI4 = new javax.swing.JPanel();
        JLI4 = new javax.swing.JLabel();
        JPI3 = new javax.swing.JPanel();
        JLI3 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        JLPregunta7 = new javax.swing.JLabel();
        JLActividad7 = new javax.swing.JLabel();
        JCBPeru = new javax.swing.JComboBox<>();
        JCBOPacifico = new javax.swing.JComboBox<>();
        JCBColombia = new javax.swing.JComboBox<>();
        JLLimitacion = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        JLPregunta8 = new javax.swing.JLabel();
        JLActividad8 = new javax.swing.JLabel();
        JCBBlancos = new javax.swing.JComboBox<>();
        JCBMestizos = new javax.swing.JComboBox<>();
        JCBIndigenas = new javax.swing.JComboBox<>();
        JLPiramide = new javax.swing.JLabel();
        JBFinalizar = new javax.swing.JButton();
        JB1 = new javax.swing.JButton();
        JB2 = new javax.swing.JButton();
        JB3 = new javax.swing.JButton();
        JB4 = new javax.swing.JButton();
        JB8 = new javax.swing.JButton();
        JB7 = new javax.swing.JButton();
        JB6 = new javax.swing.JButton();
        JB5 = new javax.swing.JButton();
        jLabel35 = new javax.swing.JLabel();
        JBSiguiente = new javax.swing.JButton();
        jPanel23 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1270, 50));

        jPanel15.setBackground(new java.awt.Color(255, 255, 255));
        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("Indicaciones para poder desarrollar de manera eficiente el juego.");
        jPanel15.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 850, 30));

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel29.setText("<html>1.-No se permite el uso de celular, tablet u otro dispositivo tegnológico durante el juego.<html>");
        jPanel15.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 720, 100));

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel28.setText("<html>2.-Leer cada pregunta antes de contestar.<html>");
        jPanel15.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, 720, 70));

        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel32.setText("<html>3.-Si responde más de lo que se le indica en la pregunta su resultado se verá afectado.<html>");
        jPanel15.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, 720, 100));

        jLabel33.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel33.setText("<html>4.-Si responde con dos respuestas en una misma pregunta, su respuesta será anulada.<html>");
        jPanel15.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 430, 720, 100));

        jLabel34.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel34.setText("<html>5.-El juego tiene preguntas de forma secuencial, así que no se podrá retroceder.<html>");
        jPanel15.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 540, 720, 60));

        jTabbedPane1.addTab("tab0", jPanel15);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JLPregunta1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        JLPregunta1.setText("Coloca la imagen en el punto cardinal que te indican");
        jPanel2.add(JLPregunta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 49, -1, 25));

        JLActividad1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        JLActividad1.setText("Actividad #1");
        jPanel2.add(JLActividad1, new org.netbeans.lib.awtextra.AbsoluteConstraints(427, 11, 120, 27));
        jPanel2.add(JLImagen1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 280, 130, 190));

        JLImagenNorte.setText("jLabel30");
        JLImagenNorte.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                JLImagenNorteMouseDragged(evt);
            }
        });
        JLImagenNorte.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                JLImagenNorteMouseReleased(evt);
            }
        });
        jPanel2.add(JLImagenNorte, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 310, 120, 120));

        JLImagenEste.setText("jLabel30");
        JLImagenEste.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                JLImagenEsteMouseDragged(evt);
            }
        });
        JLImagenEste.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                JLImagenEsteMouseReleased(evt);
            }
        });
        jPanel2.add(JLImagenEste, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 310, 120, 120));

        JLImagenSur.setText("jLabel30");
        JLImagenSur.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                JLImagenSurMouseDragged(evt);
            }
        });
        JLImagenSur.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                JLImagenSurMouseReleased(evt);
            }
        });
        jPanel2.add(JLImagenSur, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 450, 120, 120));

        JLImagenOeste.setText("jLabel30");
        JLImagenOeste.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                JLImagenOesteMouseDragged(evt);
            }
        });
        JLImagenOeste.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                JLImagenOesteMouseReleased(evt);
            }
        });
        jPanel2.add(JLImagenOeste, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 450, 120, 120));

        jPanel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel30.setText("<html>1.-EL SOL AL NORTE<p><p>2.-EL PERRO AL ESTE <p><p>3.-LA PELOTA AL SUR <p><p>4.-LA SOMBRILLA AL OESTE <html>");
        jPanel10.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 170, 150));

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel31.setText("INDICACIONES");
        jPanel10.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 90, 30));

        jPanel2.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 50, 230, 230));

        JPSur.setBackground(new java.awt.Color(204, 255, 255));
        JPSur.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        JPSur.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(JPSur, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 490, 170, 170));

        JPOeste.setBackground(new java.awt.Color(204, 255, 255));
        JPOeste.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        JPOeste.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(JPOeste, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 170, 170));

        JPEste.setBackground(new java.awt.Color(204, 255, 255));
        JPEste.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        JPEste.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(JPEste, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 300, 170, 170));

        JPNorte.setBackground(new java.awt.Color(204, 255, 255));
        JPNorte.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        JPNorte.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(JPNorte, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 170, 170));

        jTabbedPane1.addTab("tab1", jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JLPregunta2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        JLPregunta2.setText("Arrastra y coloca debajo de la imagen la palabra que corresponde a cada uno");
        jPanel3.add(JLPregunta2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 49, 520, 25));

        JLActividad2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        JLActividad2.setText("Actividad #2");
        jPanel3.add(JLActividad2, new org.netbeans.lib.awtextra.AbsoluteConstraints(427, 11, 120, 27));

        jLabel4.setText("LUNA");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 120, 60, 40));

        jLabel5.setText("TIERRA");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 120, 60, 40));

        jLabel6.setText("SOL");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 60, 40));
        jPanel3.add(JLImagenLuna, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 170, 180, 180));
        jPanel3.add(JLImagenTierra, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 170, 180, 180));
        jPanel3.add(JLImagenSol, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 180, 180));

        jLabel23.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 380, 190, 80));

        jLabel24.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 380, 190, 80));

        jLabel25.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 380, 190, 80));

        JBPlaneta.setText("PLANETA");
        JBPlaneta.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                JBPlanetaMouseDragged(evt);
            }
        });
        JBPlaneta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                JBPlanetaMouseReleased(evt);
            }
        });
        jPanel3.add(JBPlaneta, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 530, 90, 30));

        JBSatelite.setText("SATÉLITE");
        JBSatelite.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                JBSateliteMouseDragged(evt);
            }
        });
        JBSatelite.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                JBSateliteMouseReleased(evt);
            }
        });
        jPanel3.add(JBSatelite, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 530, 90, 30));

        JBEstrella.setText("ESTRELLA");
        JBEstrella.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                JBEstrellaMouseDragged(evt);
            }
        });
        JBEstrella.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                JBEstrellaMouseReleased(evt);
            }
        });
        jPanel3.add(JBEstrella, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 530, 100, 30));

        jTabbedPane1.addTab("tab2", jPanel3);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JLActividad3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        JLActividad3.setText("Actividad #3");
        jPanel4.add(JLActividad3, new org.netbeans.lib.awtextra.AbsoluteConstraints(427, 11, 110, 27));

        JLPregunta3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        JLPregunta3.setText(" Selecciona las provincias que corresponden a la Costa");
        jPanel4.add(JLPregunta3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 49, 360, 25));

        JCBEsmeraldas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "?", "El Oro", "Esmeraldas", "Guayas", "Pichincha", "Manabí", "Sucumbios" }));
        JCBEsmeraldas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCBEsmeraldasActionPerformed(evt);
            }
        });
        jPanel4.add(JCBEsmeraldas, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, 110, -1));

        JCBManabi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "?", "El Oro", "Esmeraldas", "Guayas", "Pichincha", "Manabí", "Sucumbios" }));
        JCBManabi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCBManabiActionPerformed(evt);
            }
        });
        jPanel4.add(JCBManabi, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 110, -1));

        JCBEloro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "?", "El Oro", "Esmeraldas", "Guayas", "Pichincha", "Manabí", "Sucumbios" }));
        JCBEloro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCBEloroActionPerformed(evt);
            }
        });
        jPanel4.add(JCBEloro, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 570, 110, -1));

        JCBGuayas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "?", "El Oro", "Esmeraldas", "Guayas", "Pichincha", "Manabí", "Sucumbios" }));
        JCBGuayas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCBGuayasActionPerformed(evt);
            }
        });
        jPanel4.add(JCBGuayas, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 500, 110, -1));

        JLEcuador.setText("jLabel7");
        jPanel4.add(JLEcuador, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 610, 540));

        jTabbedPane1.addTab("tab3", jPanel4);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JLActividad4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        JLActividad4.setText("Actividad #4");
        jPanel5.add(JLActividad4, new org.netbeans.lib.awtextra.AbsoluteConstraints(427, 11, 110, 27));

        JLPregunta4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        JLPregunta4.setText("Arrastrar y clasificar las imágenes al lugar que pertenecen");
        jPanel5.add(JLPregunta4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 49, 380, 25));

        JPEducacion.setBackground(new java.awt.Color(255, 255, 255));
        JPEducacion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        JPEducacion.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                JPEducacionMouseDragged(evt);
            }
        });
        JPEducacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                JPEducacionMouseReleased(evt);
            }
        });
        JPEducacion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        JPEducacion.add(JLEducacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 110, 90));

        JLTexto1.setText("Educacion");
        JPEducacion.add(JLTexto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));

        jPanel5.add(JPEducacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 150, 130));

        JPRespeto.setBackground(new java.awt.Color(255, 255, 255));
        JPRespeto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        JPRespeto.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                JPRespetoMouseDragged(evt);
            }
        });
        JPRespeto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                JPRespetoMouseReleased(evt);
            }
        });
        JPRespeto.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        JPRespeto.add(JLRespeto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 110, 100));

        JLTexto2.setText("Respeto por los demas");
        JPRespeto.add(JLTexto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        jPanel5.add(JPRespeto, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 150, 130));

        JPTareas.setBackground(new java.awt.Color(255, 255, 255));
        JPTareas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        JPTareas.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                JPTareasMouseDragged(evt);
            }
        });
        JPTareas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                JPTareasMouseReleased(evt);
            }
        });
        JPTareas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        JPTareas.add(JLCumplir, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 110, 90));

        JLTexto3.setText("<html>Cumplir con las tareas<p>en casa<html>");
        JPTareas.add(JLTexto3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 140, 40));

        jPanel5.add(JPTareas, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 450, 150, 140));

        JPCuidar.setBackground(new java.awt.Color(255, 255, 255));
        JPCuidar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        JPCuidar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                JPCuidarMouseDragged(evt);
            }
        });
        JPCuidar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                JPCuidarMouseReleased(evt);
            }
        });
        JPCuidar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        JPCuidar.add(JLCuidar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 130, 100));

        JLTexto4.setText("Cuidar al planeta");
        JPCuidar.add(JLTexto4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, 20));

        jPanel5.add(JPCuidar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 450, 150, 140));

        JPFamilia.setBackground(new java.awt.Color(255, 255, 255));
        JPFamilia.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        JPFamilia.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                JPFamiliaMouseDragged(evt);
            }
        });
        JPFamilia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                JPFamiliaMouseReleased(evt);
            }
        });
        JPFamilia.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        JPFamilia.add(JLFamilia, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 110, 90));

        JLTexto5.setText("Familia");
        JPFamilia.add(JLTexto5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, -1, -1));

        jPanel5.add(JPFamilia, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 150, 130));

        JPSalud.setBackground(new java.awt.Color(255, 255, 255));
        JPSalud.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        JPSalud.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                JPSaludMouseDragged(evt);
            }
        });
        JPSalud.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                JPSaludMouseReleased(evt);
            }
        });
        JPSalud.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        JPSalud.add(JLSalud, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 110, 90));

        JLTexto7.setText("Salud");
        JPSalud.add(JLTexto7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, -1, -1));

        jPanel5.add(JPSalud, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 270, 150, 130));

        jPanel12.setBackground(new java.awt.Color(204, 255, 204));
        jPanel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Debres");
        jPanel12.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, 20));

        jPanel5.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 80, 200, 540));

        jPanel14.setBackground(new java.awt.Color(204, 255, 255));
        jPanel14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setText("Derechos ");
        jPanel14.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, 20));

        jPanel5.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 80, 200, 540));

        jTabbedPane1.addTab("tab4", jPanel5);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JPE.setBackground(new java.awt.Color(255, 255, 255));
        JPE.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        JPE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JPEMouseClicked(evt);
            }
        });
        JPE.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JLbandera.setText("jLabel9");
        JPE.add(JLbandera, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 130, 130));

        jPanel6.add(JPE, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 210, 180));

        JPM.setBackground(new java.awt.Color(255, 255, 255));
        JPM.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        JPM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JPMMouseClicked(evt);
            }
        });
        JPM.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JLMachu.setText("jLabel9");
        JPM.add(JLMachu, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 130, 130));

        jPanel6.add(JPM, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, 220, 180));

        jLabel8.setText("¿Cuál de los dos es símbolo patrio del Ecuador?");
        jPanel6.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 280, 30));

        JLPregunta5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        JLPregunta5.setText("Señale e identifique cuales son los símbolos patrios del Ecuador");
        jPanel6.add(JLPregunta5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 49, 430, 25));

        JLActividad5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        JLActividad5.setText("Actividad #5");
        jPanel6.add(JLActividad5, new org.netbeans.lib.awtextra.AbsoluteConstraints(427, 11, 120, 27));

        jLabel9.setText("¿Cuál de los dos es símbolo patrio del Ecuador?");
        jPanel6.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 120, 280, 30));

        JPE1.setBackground(new java.awt.Color(255, 255, 255));
        JPE1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        JPE1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JPE1MouseClicked(evt);
            }
        });
        JPE1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JLFlora.setText("jLabel9");
        JPE1.add(JLFlora, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 130, 130));

        jPanel6.add(JPE1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 170, 210, 180));

        JPM1.setBackground(new java.awt.Color(255, 255, 255));
        JPM1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        JPM1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JPM1MouseClicked(evt);
            }
        });
        JPM1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JLEscudo.setText("jLabel9");
        JPM1.add(JLEscudo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 130, 130));

        jPanel6.add(JPM1, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 170, 210, 180));

        jLabel10.setText("¿Cuál de los dos es símbolo patrio del Ecuador?");
        jPanel6.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 410, 280, 30));

        JPE2.setBackground(new java.awt.Color(255, 255, 255));
        JPE2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        JPE2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JPE2MouseClicked(evt);
            }
        });
        JPE2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JLCostumbre.setText("jLabel9");
        JPE2.add(JLCostumbre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 130, 130));

        jPanel6.add(JPE2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 460, 210, 180));

        JPM2.setBackground(new java.awt.Color(255, 255, 255));
        JPM2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        JPM2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JPM2MouseClicked(evt);
            }
        });
        JPM2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JLCostitucion.setText("jLabel9");
        JPM2.add(JLCostitucion, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 130, 130));

        jPanel6.add(JPM2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 460, 210, 180));

        jPanel8.setBackground(new java.awt.Color(0, 0, 0));
        jPanel6.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 100, 10, 290));

        jPanel7.setBackground(new java.awt.Color(0, 0, 0));
        jPanel6.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 390, 540, 10));

        jTabbedPane1.addTab("tab5", jPanel6);

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JLPregunta6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        JLPregunta6.setText("Seleccione las acciones que se deben realizar para cuidar los recursos naturales.");
        jPanel9.add(JLPregunta6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 49, 520, 25));

        JLActividad6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        JLActividad6.setText("Actividad #6");
        jPanel9.add(JLActividad6, new org.netbeans.lib.awtextra.AbsoluteConstraints(427, 11, 110, 27));

        JPI5.setBackground(new java.awt.Color(255, 255, 255));
        JPI5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        JPI5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JPI5MouseClicked(evt);
            }
        });
        JPI5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JLI5.setText("jLabel11");
        JPI5.add(JLI5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 310, 190));

        jPanel9.add(JPI5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 350, 520, 230));

        JPI1.setBackground(new java.awt.Color(255, 255, 255));
        JPI1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        JPI1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JPI1MouseClicked(evt);
            }
        });
        JPI1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JLI1.setText("jLabel11");
        JPI1.add(JLI1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 220, 190));

        jPanel9.add(JPI1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 260, 230));

        JPI2.setBackground(new java.awt.Color(255, 255, 255));
        JPI2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        JPI2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JPI2MouseClicked(evt);
            }
        });
        JPI2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JLI2.setText("jLabel11");
        JPI2.add(JLI2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 200, 190));

        jPanel9.add(JPI2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 120, 260, 230));

        JPI4.setBackground(new java.awt.Color(255, 255, 255));
        JPI4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        JPI4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JPI4MouseClicked(evt);
            }
        });
        JPI4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JLI4.setText("jLabel11");
        JPI4.add(JLI4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 200, 190));

        jPanel9.add(JPI4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, 260, 230));

        JPI3.setBackground(new java.awt.Color(255, 255, 255));
        JPI3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        JPI3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JPI3MouseClicked(evt);
            }
        });
        JPI3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JLI3.setText("jLabel11");
        JPI3.add(JLI3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 200, 190));

        jPanel9.add(JPI3, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 120, 260, 230));

        jTabbedPane1.addTab("tab6", jPanel9);

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JLPregunta7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        JLPregunta7.setText("Seleccione  los países y el oceáno que limitan con Ecuador");
        jPanel11.add(JLPregunta7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 49, 400, 25));

        JLActividad7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        JLActividad7.setText("Actividad #7");
        jPanel11.add(JLActividad7, new org.netbeans.lib.awtextra.AbsoluteConstraints(427, 11, 130, 27));

        JCBPeru.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        JCBPeru.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "?", "O.Atlantico", "O.Pacifico", "Peru", "Brazil", "Colombia", "Venezuela" }));
        JCBPeru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCBPeruActionPerformed(evt);
            }
        });
        jPanel11.add(JCBPeru, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 510, 170, 50));

        JCBOPacifico.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        JCBOPacifico.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "?", "O.Atlantico", "O.Pacifico", "Peru", "Brazil", "Colombia", "Venezuela" }));
        JCBOPacifico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCBOPacificoActionPerformed(evt);
            }
        });
        jPanel11.add(JCBOPacifico, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 390, 170, 50));

        JCBColombia.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        JCBColombia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "?", "O.Atlantico", "O.Pacifico", "Peru", "Brazil", "Colombia", "Venezuela" }));
        JCBColombia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCBColombiaActionPerformed(evt);
            }
        });
        jPanel11.add(JCBColombia, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 90, 170, 50));

        JLLimitacion.setText("jLabel11");
        jPanel11.add(JLLimitacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 630, 490));

        jTabbedPane1.addTab("tab7", jPanel11);

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JLPregunta8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        JLPregunta8.setText("Ubicar a lado de la pirámide las diferentes sociedades que se desarrollaron en la época colonial.");
        jPanel13.add(JLPregunta8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 49, 620, 25));

        JLActividad8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        JLActividad8.setText("Actividad #8");
        jPanel13.add(JLActividad8, new org.netbeans.lib.awtextra.AbsoluteConstraints(427, 11, 110, 27));

        JCBBlancos.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        JCBBlancos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "?", "Blancos", "Indígenas", "Mestizos" }));
        JCBBlancos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCBBlancosActionPerformed(evt);
            }
        });
        jPanel13.add(JCBBlancos, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 220, 190, 50));

        JCBMestizos.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        JCBMestizos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "?", "Blancos", "Indígenas", "Mestizos" }));
        JCBMestizos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCBMestizosActionPerformed(evt);
            }
        });
        jPanel13.add(JCBMestizos, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 350, 190, 50));

        JCBIndigenas.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        JCBIndigenas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "?", "Blancos", "Indígenas", "Mestizos" }));
        JCBIndigenas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCBIndigenasActionPerformed(evt);
            }
        });
        jPanel13.add(JCBIndigenas, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 480, 190, 50));

        JLPiramide.setText("jLabel11");
        jPanel13.add(JLPiramide, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 480, 520));

        jTabbedPane1.addTab("tab8", jPanel13);

        jPanel1.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, 970, 720));

        JBFinalizar.setBackground(new java.awt.Color(255, 126, 57));
        JBFinalizar.setText("Finalizar Prueba");
        JBFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBFinalizarActionPerformed(evt);
            }
        });
        jPanel1.add(JBFinalizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 470, 150, 50));

        JB1.setBackground(new java.awt.Color(255, 255, 255));
        JB1.setText("1");
        JB1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                JB1MouseDragged(evt);
            }
        });
        jPanel1.add(JB1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 50, 40));

        JB2.setBackground(new java.awt.Color(255, 255, 255));
        JB2.setText("2");
        jPanel1.add(JB2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 50, 40));

        JB3.setBackground(new java.awt.Color(255, 255, 255));
        JB3.setText("3");
        jPanel1.add(JB3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 50, 40));

        JB4.setBackground(new java.awt.Color(255, 255, 255));
        JB4.setText("4");
        jPanel1.add(JB4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 50, 40));

        JB8.setBackground(new java.awt.Color(255, 255, 255));
        JB8.setText("8");
        jPanel1.add(JB8, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 50, 40));

        JB7.setBackground(new java.awt.Color(255, 255, 255));
        JB7.setText("7");
        jPanel1.add(JB7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 50, 40));

        JB6.setBackground(new java.awt.Color(255, 255, 255));
        JB6.setText("6");
        jPanel1.add(JB6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 50, 40));

        JB5.setBackground(new java.awt.Color(255, 255, 255));
        JB5.setText("5");
        jPanel1.add(JB5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 50, 40));

        jLabel35.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel35.setText("Banco de Preguntas");
        jPanel1.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 140, 40));

        JBSiguiente.setBackground(new java.awt.Color(255, 126, 57));
        JBSiguiente.setText("Empezar");
        JBSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBSiguienteActionPerformed(evt);
            }
        });
        jPanel1.add(JBSiguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 470, 150, 40));

        jPanel23.setBackground(new java.awt.Color(255, 255, 255));
        jPanel23.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 220, 170));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1270, 820));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBFinalizarActionPerformed
        String calificaion1 =null;
        String calificaion2 =null;
        String calificaion3 =null;
        String calificaion4 =null;
        String calificaion5 =null;
        String calificaion6 =null;
        String calificaion7 =null;
        String calificaion8 =null;
        //nota actividad 1
       
        notafinal1= A1+A2+A3+A4;
        calificaion1 = Integer.toString(notafinal1);
        
        
        //nota actividad 2
        notafinal2 =B1+B2+B3;
        calificaion2 = Integer.toString(notafinal2);
       
        
        
        //nota actividad 3
        
        notafinal3 =C1+C2+C3+C4;
        calificaion3 = Integer.toString(notafinal3);
       
        
         //nota actividad 4
         
        notafinal4 =D1+D2+D3+D4+D5+D6;
        calificaion4 = Integer.toString(notafinal4);
        
        
        
        //nota actividad 5
         
        notafinal5 =E1+E2+E3+E4;
        calificaion5 = Integer.toString(notafinal5);
        
        
         //nota actividad 6
         
        notafinal6 =F1+F2+F3+F4+F5;
        if(notafinal6 <=1){
            notafinal6=1;
        }
        calificaion6 = Integer.toString(notafinal6);
       
        
        
        //nota actividad 7
         
        notafinal7 =G1+G2+G3;
        calificaion7 = Integer.toString(notafinal7);
        
        
        
        //nota actividad 8
         
        notafinal8 =H1+H2+H3;
        calificaion8 = Integer.toString(notafinal8);
        
        
        
        SumaTotal= notafinal1+notafinal2+notafinal3+notafinal4+notafinal5+notafinal6+notafinal7+notafinal8;
        
        SumaTotal = SumaTotal*0.34482;
         BigDecimal bd = new BigDecimal(SumaTotal).setScale(1,RoundingMode.HALF_UP);
        calificaion8  = String.valueOf(bd);
        
        
         FrmModulos.JLN2.setText("1");
       if(FrmModulos.JLN1.getText().equals("1") && FrmModulos.JLN3.getText().equals("1")){
           s1= 99;
           FrmModulos.JBFin.setEnabled(true);
           FrmModulos.JLPorcentaje.setText("100%");
        }else if(FrmModulos.JLN1.getText().equals("1") || FrmModulos.JLN3.getText().equals("1") ){
           s1= 66;
           FrmModulos.JLPorcentaje.setText("66%");
        }else{
           s1=33;
           FrmModulos.JLPorcentaje.setText("33%");
        }
        
       Barra.setValue(s1);
       this.setVisible(false);
        
       metodos.LlenarNotaSociales(FrmModulos.LBCorreo.getText(),calificaion8);
        
    }//GEN-LAST:event_JBFinalizarActionPerformed

    private void JPEducacionMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPEducacionMouseDragged
        if(evt.getModifiersEx() == MouseEvent.BUTTON1_DOWN_MASK){
            
            jPanel5.setLayout(new BorderLayout());
             JPEducacion.setLocation( JPEducacion.getLocation().x+ evt.getX() -  JPEducacion.getWidth()/2 ,
             JPEducacion.getLocation().y+ evt.getY() -  JPEducacion.getHeight());
             if (JPEducacion.getLocation().x <531 && JPEducacion.getLocation().x >480 && JPEducacion.getLocation().y >80  &&  JPEducacion.getLocation().y <490  ){
              D1=1;
           }else{
              D1=0;
             }
            
       
              JPEducacion.repaint();
            
            } 
    }//GEN-LAST:event_JPEducacionMouseDragged

    private void JPRespetoMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPRespetoMouseDragged
       
        
        if(evt.getModifiersEx() == MouseEvent.BUTTON1_DOWN_MASK){
            
            jPanel5.setLayout(new BorderLayout());
             JPRespeto.setLocation( JPRespeto.getLocation().x+ evt.getX() -  JPRespeto.getWidth()/2 ,
             JPRespeto.getLocation().y+ evt.getY() -  JPRespeto.getHeight());
             if (JPRespeto.getLocation().x <770 && JPRespeto.getLocation().x >720 && JPRespeto.getLocation().y >80  &&  JPRespeto.getLocation().y <490  ){
              D2=1;
           }else{
              D2=0;
             }
            
              JPRespeto.repaint();
            
            } 
    }//GEN-LAST:event_JPRespetoMouseDragged

    private void JPTareasMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPTareasMouseDragged
        if(evt.getModifiersEx() == MouseEvent.BUTTON1_DOWN_MASK){
            
            jPanel5.setLayout(new BorderLayout());
             JPTareas.setLocation( JPTareas.getLocation().x+ evt.getX() -  JPTareas.getWidth()/2 ,
             JPTareas.getLocation().y+ evt.getY() -  JPTareas.getHeight());
             if (JPTareas.getLocation().x <770 && JPTareas.getLocation().x >720 && JPTareas.getLocation().y >80  &&  JPTareas.getLocation().y <490  ){
              D3=1;
           }else{
              D3=0;
             }
             
              JPTareas.repaint();
            
            } 
    }//GEN-LAST:event_JPTareasMouseDragged

    private void JPCuidarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPCuidarMouseDragged
        if(evt.getModifiersEx() == MouseEvent.BUTTON1_DOWN_MASK){
            
            jPanel5.setLayout(new BorderLayout());
             JPCuidar.setLocation( JPCuidar.getLocation().x+ evt.getX() -  JPCuidar.getWidth()/2 ,
             JPCuidar.getLocation().y+ evt.getY() -  JPCuidar.getHeight());
             if (JPCuidar.getLocation().x <770 && JPCuidar.getLocation().x >720 && JPCuidar.getLocation().y >80  &&  JPCuidar.getLocation().y <490  ){
              D4=1;
           }else{
              D4=0;
             }
             
              JPCuidar.repaint();
            
            } 
    }//GEN-LAST:event_JPCuidarMouseDragged

    private void JPEducacionMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPEducacionMouseReleased
        if(JPEducacion.getLocation().x <0 || JPEducacion.getLocation().x >890 ||  JPEducacion.getLocation().y <0 ||  JPEducacion.getLocation().y >600   ){
          JPEducacion.setLocation(40, 270);
      }
    }//GEN-LAST:event_JPEducacionMouseReleased

    private void JPRespetoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPRespetoMouseReleased
        if(JPRespeto.getLocation().x <0 || JPRespeto.getLocation().x >890 ||  JPRespeto.getLocation().y <0 ||  JPRespeto.getLocation().y >600   ){
          JPRespeto.setLocation(230, 110);
      }
    }//GEN-LAST:event_JPRespetoMouseReleased

    private void JPTareasMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPTareasMouseReleased
       if(JPTareas.getLocation().x <0 || JPTareas.getLocation().x >890 ||  JPTareas.getLocation().y <0 ||  JPTareas.getLocation().y >600   ){
          JPTareas.setLocation(40, 449);
      }
    }//GEN-LAST:event_JPTareasMouseReleased

    private void JPCuidarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPCuidarMouseReleased
        if(JPCuidar.getLocation().x <0 || JPCuidar.getLocation().x >890 ||  JPCuidar.getLocation().y <0 ||  JPCuidar.getLocation().y >600   ){
          JPCuidar.setLocation(230, 449);
      }
    }//GEN-LAST:event_JPCuidarMouseReleased

    private void JLImagenNorteMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JLImagenNorteMouseDragged
        if(evt.getModifiersEx() == MouseEvent.BUTTON1_DOWN_MASK){
            
            jPanel2.setLayout(new BorderLayout());
             JLImagenNorte.setLocation( JLImagenNorte.getLocation().x+ evt.getX() -  JLImagenNorte.getWidth()/2 ,
             JLImagenNorte.getLocation().y+ evt.getY() -  JLImagenNorte.getHeight());
             
              if (JLImagenNorte.getLocation().x <270 && JLImagenNorte.getLocation().x >220 && JLImagenNorte.getLocation().y >100  &&  JLImagenNorte.getLocation().y <150  ){
              A1=1;
           }else{
              A1=0;
             }
             
              JLImagenNorte.repaint();
            } 
    }//GEN-LAST:event_JLImagenNorteMouseDragged

    private void JLImagenEsteMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JLImagenEsteMouseDragged
        if(evt.getModifiersEx() == MouseEvent.BUTTON1_DOWN_MASK){
            
            jPanel2.setLayout(new BorderLayout());
             JLImagenEste.setLocation( JLImagenEste.getLocation().x+ evt.getX() -  JLImagenEste.getWidth()/2 ,
             JLImagenEste.getLocation().y+ evt.getY() -  JLImagenEste.getHeight());
             if (JLImagenEste.getLocation().x <470 && JLImagenEste.getLocation().x >420 && JLImagenEste.getLocation().y >300  &&  JLImagenEste.getLocation().y <350  ){
              A2=1;
           }else{
              A2=0;
             }
              JLImagenEste.repaint();
            } 
    }//GEN-LAST:event_JLImagenEsteMouseDragged

    private void JLImagenSurMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JLImagenSurMouseDragged
        if(evt.getModifiersEx() == MouseEvent.BUTTON1_DOWN_MASK){
            
            jPanel2.setLayout(new BorderLayout());
             JLImagenSur.setLocation( JLImagenSur.getLocation().x+ evt.getX() -  JLImagenSur.getWidth()/2 ,
             JLImagenSur.getLocation().y+ evt.getY() -  JLImagenSur.getHeight());
             if (JLImagenSur.getLocation().x <270 && JLImagenSur.getLocation().x >220 && JLImagenSur.getLocation().y >490  &&  JLImagenSur.getLocation().y <540  ){
              A3=1;
           }else{
              A3=0;
             }
              JLImagenSur.repaint();
            } 
    }//GEN-LAST:event_JLImagenSurMouseDragged

    private void JLImagenOesteMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JLImagenOesteMouseDragged
        if(evt.getModifiersEx() == MouseEvent.BUTTON1_DOWN_MASK){
            
            jPanel2.setLayout(new BorderLayout());
             JLImagenOeste.setLocation( JLImagenOeste.getLocation().x+ evt.getX() -  JLImagenOeste.getWidth()/2 ,
             JLImagenOeste.getLocation().y+ evt.getY() -  JLImagenOeste.getHeight());
             if (JLImagenOeste.getLocation().x <70 && JLImagenOeste.getLocation().x >20 && JLImagenOeste.getLocation().y >290  &&  JLImagenOeste.getLocation().y <340  ){
              A4=1;
           }else{
              A4=0;
             }
             
              JLImagenOeste.repaint();
            } 
    }//GEN-LAST:event_JLImagenOesteMouseDragged

    private void JLImagenNorteMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JLImagenNorteMouseReleased
        if(JLImagenNorte.getLocation().x <0 || JLImagenNorte.getLocation().x >890 ||  JLImagenNorte.getLocation().y <0 ||  JLImagenNorte.getLocation().y >600   ){
          JLImagenNorte.setLocation(660, 310);
      }
    }//GEN-LAST:event_JLImagenNorteMouseReleased

    private void JLImagenEsteMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JLImagenEsteMouseReleased
       if(JLImagenEste.getLocation().x <0 || JLImagenEste.getLocation().x >890 ||  JLImagenEste.getLocation().y <0 ||  JLImagenEste.getLocation().y >600   ){
          JLImagenEste.setLocation(810, 310);
      }
    }//GEN-LAST:event_JLImagenEsteMouseReleased

    private void JLImagenSurMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JLImagenSurMouseReleased
        if(JLImagenSur.getLocation().x <0 || JLImagenSur.getLocation().x >890 ||  JLImagenSur.getLocation().y <0 ||  JLImagenSur.getLocation().y >600   ){
          JLImagenSur.setLocation(660, 450);
      }
    }//GEN-LAST:event_JLImagenSurMouseReleased

    private void JLImagenOesteMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JLImagenOesteMouseReleased
        if(JLImagenOeste.getLocation().x <0 || JLImagenOeste.getLocation().x >890 ||  JLImagenOeste.getLocation().y <0 ||  JLImagenOeste.getLocation().y >600   ){
          JLImagenOeste.setLocation(810, 450);
      } 
    }//GEN-LAST:event_JLImagenOesteMouseReleased

    private void JBPlanetaMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBPlanetaMouseDragged
         if(evt.getModifiersEx() == MouseEvent.BUTTON1_DOWN_MASK){
            
            jPanel3.setLayout(new BorderLayout());
             JBPlaneta.setLocation( JBPlaneta.getLocation().x+ evt.getX() -  JBPlaneta.getWidth()/2 ,
             JBPlaneta.getLocation().y+ evt.getY() -  JBPlaneta.getHeight());
            
             if (JBPlaneta.getLocation().x <502 && JBPlaneta.getLocation().x >400 && JBPlaneta.getLocation().y >380  &&  JBPlaneta.getLocation().y <430  ){
              B1=1;
           }else{
              B1=0;
             }
              
              JBPlaneta.repaint();
            } 
    }//GEN-LAST:event_JBPlanetaMouseDragged

    private void JBSateliteMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBSateliteMouseDragged
         if(evt.getModifiersEx() == MouseEvent.BUTTON1_DOWN_MASK){
            
            jPanel3.setLayout(new BorderLayout());
             JBSatelite.setLocation( JBSatelite.getLocation().x+ evt.getX() -  JBSatelite.getWidth()/2 ,
             JBSatelite.getLocation().y+ evt.getY() -  JBSatelite.getHeight());
             if (JBSatelite.getLocation().x <762 && JBSatelite.getLocation().x >660 && JBSatelite.getLocation().y >380  &&  JBSatelite.getLocation().y <430  ){
              B2=1;
           }else{
              B2=0;
             }
             
              JBSatelite.repaint();
            } 
    }//GEN-LAST:event_JBSateliteMouseDragged

    private void JBEstrellaMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBEstrellaMouseDragged
        if(evt.getModifiersEx() == MouseEvent.BUTTON1_DOWN_MASK){
            
            jPanel3.setLayout(new BorderLayout());
             JBEstrella.setLocation( JBEstrella.getLocation().x+ evt.getX() -  JBEstrella.getWidth()/2 ,
             JBEstrella.getLocation().y+ evt.getY() -  JBEstrella.getHeight());
             if (JBEstrella.getLocation().x <232 && JBEstrella.getLocation().x >130 && JBEstrella.getLocation().y >280  &&  JBEstrella.getLocation().y <430  ){
              B3=1;
           }else{
              B3=0;
             }
             
              JBEstrella.repaint();
            } 
    }//GEN-LAST:event_JBEstrellaMouseDragged

    private void JBPlanetaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBPlanetaMouseReleased
        if(JBPlaneta.getLocation().x <0 || JBPlaneta.getLocation().x >890 ||  JBPlaneta.getLocation().y <0 ||  JBPlaneta.getLocation().y >600   ){
          JBPlaneta.setLocation(190, 530);
      }
    }//GEN-LAST:event_JBPlanetaMouseReleased

    private void JBSateliteMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBSateliteMouseReleased
       if(JBSatelite.getLocation().x <0 || JBSatelite.getLocation().x >890 ||  JBSatelite.getLocation().y <0 ||  JBSatelite.getLocation().y >600   ){
          JBSatelite.setLocation(450, 530);
      }
    }//GEN-LAST:event_JBSateliteMouseReleased

    private void JBEstrellaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBEstrellaMouseReleased
        if(JBEstrella.getLocation().x <0 || JBEstrella.getLocation().x >890 ||  JBEstrella.getLocation().y <0 ||  JBEstrella.getLocation().y >600   ){
          JBEstrella.setLocation(716, 530);
      }
    }//GEN-LAST:event_JBEstrellaMouseReleased

    private void JCBEsmeraldasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCBEsmeraldasActionPerformed
        if(JCBEsmeraldas.getSelectedItem().equals("Esmeraldas")){
            C1=1;
        }else{
            C1=0;
        }
    }//GEN-LAST:event_JCBEsmeraldasActionPerformed

    private void JCBManabiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCBManabiActionPerformed
        if(JCBManabi.getSelectedItem().equals("Manabi")){
            C2=1;
        }else{
            C2=0;
        }
    }//GEN-LAST:event_JCBManabiActionPerformed

    private void JCBGuayasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCBGuayasActionPerformed
        if(JCBGuayas.getSelectedItem().equals("Guayas")){
            C3=1;
        }else{
            C3=0;
        }
    }//GEN-LAST:event_JCBGuayasActionPerformed

    private void JCBEloroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCBEloroActionPerformed
        if(JCBEloro.getSelectedItem().equals("El Oro")){
            C4=1;
        }else{
            C4=0;
        }
    }//GEN-LAST:event_JCBEloroActionPerformed

    private void JPFamiliaMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPFamiliaMouseDragged
        if(evt.getModifiersEx() == MouseEvent.BUTTON1_DOWN_MASK){
            
            jPanel5.setLayout(new BorderLayout());
             JPFamilia.setLocation( JPFamilia.getLocation().x+ evt.getX() -  JPFamilia.getWidth()/2 ,
             JPFamilia.getLocation().y+ evt.getY() -  JPFamilia.getHeight());
             if (JPFamilia.getLocation().x <530 && JPFamilia.getLocation().x >480 && JPFamilia.getLocation().y >80  &&  JPFamilia.getLocation().y <490  ){
             D5=1;
           }else{
             D5=0;
             }
             
              JPFamilia.repaint();
            } 
    }//GEN-LAST:event_JPFamiliaMouseDragged

    private void JPFamiliaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPFamiliaMouseReleased
       if(JPFamilia.getLocation().x <0 || JPFamilia.getLocation().x >890 ||  JPFamilia.getLocation().y <0 ||  JPFamilia.getLocation().y >600   ){
          JPFamilia.setLocation(40, 110);
      }
    }//GEN-LAST:event_JPFamiliaMouseReleased

    private void JPSaludMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPSaludMouseDragged
       if(evt.getModifiersEx() == MouseEvent.BUTTON1_DOWN_MASK){
            
            jPanel5.setLayout(new BorderLayout());
             JPSalud.setLocation( JPSalud.getLocation().x+ evt.getX() -  JPSalud.getWidth()/2 ,
             JPSalud.getLocation().y+ evt.getY() -  JBEstrella.getHeight());
             if (JPSalud.getLocation().x <530 && JPSalud.getLocation().x >480 && JPSalud.getLocation().y >80  &&  JPSalud.getLocation().y <490  ){
              D6=1;
           }else{
              D6=0;
             }
             
              JPSalud.repaint();
            } 
    }//GEN-LAST:event_JPSaludMouseDragged

    private void JPSaludMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPSaludMouseReleased
        if(JPSalud.getLocation().x <0 || JPSalud.getLocation().x >890 ||  JPSalud.getLocation().y <0 ||  JPSalud.getLocation().y >600   ){
          JPSalud.setLocation(230, 270);
      }
    }//GEN-LAST:event_JPSaludMouseReleased

    private void JPEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPEMouseClicked
       JPE.setBackground(Color.green);
       JPM.setBackground(Color.white);
        
        E1=1;
    }//GEN-LAST:event_JPEMouseClicked

    private void JPMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPMMouseClicked
        JPM.setBackground(Color.green);
        JPE.setBackground(Color.white);
        
        E1=0;
    }//GEN-LAST:event_JPMMouseClicked

    private void JPE1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPE1MouseClicked
        JPE1.setBackground(Color.green);
        JPM1.setBackground(Color.white);
        
        E2=0;
    }//GEN-LAST:event_JPE1MouseClicked

    private void JPM1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPM1MouseClicked
       JPM1.setBackground(Color.green);
       JPE1.setBackground(Color.white);
        
        E2=1;
    }//GEN-LAST:event_JPM1MouseClicked

    private void JPE2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPE2MouseClicked
        JPE2.setBackground(Color.green);
        JPM2.setBackground(Color.white);
        
        E3=0;
    }//GEN-LAST:event_JPE2MouseClicked

    private void JPM2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPM2MouseClicked
        JPE2.setBackground(Color.white);
        JPM2.setBackground(Color.green);
        
        E3=1;
    }//GEN-LAST:event_JPM2MouseClicked

    private void JPI5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPI5MouseClicked
        if(evt.getClickCount()== 1){
        JPI5.setBackground(Color.green);
        F3=1;
       }else{
           JPI5.setBackground(Color.white);
           F3=0;
       }
    }//GEN-LAST:event_JPI5MouseClicked

    private void JPI1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPI1MouseClicked
       if(evt.getClickCount()== 1){
        JPI1.setBackground(Color.green);
        F1=1;
       }else{
        JPI1.setBackground(Color.white);
        F1=0;
       }
        
    }//GEN-LAST:event_JPI1MouseClicked

    private void JPI2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPI2MouseClicked
       if(evt.getClickCount()== 1){
        JPI2.setBackground(Color.green);
        F4=-1;
       }else{
        JPI2.setBackground(Color.white);
        F4=0;  
       }
    }//GEN-LAST:event_JPI2MouseClicked

    private void JPI4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPI4MouseClicked
        if(evt.getClickCount()== 1){
        JPI4.setBackground(Color.green);
        F2=1;
       }else{
           JPI4.setBackground(Color.white);
           F2=0;
       }
    }//GEN-LAST:event_JPI4MouseClicked

    private void JPI3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPI3MouseClicked
        if(evt.getClickCount()== 1){
        JPI3.setBackground(Color.green);
        F5=-1;
       }else{
           JPI3.setBackground(Color.white);
           F5=0;
       }
    }//GEN-LAST:event_JPI3MouseClicked

    private void JCBBlancosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCBBlancosActionPerformed
         if(JCBBlancos.getSelectedItem().equals("Blancos")){
           H1=1;
        }else{
           H1=0;
        }
    }//GEN-LAST:event_JCBBlancosActionPerformed

    private void JCBMestizosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCBMestizosActionPerformed
        if(JCBMestizos.getSelectedItem().equals("Mestizos")){
           H2=1;
        }else{
           H2=0;
        }
    }//GEN-LAST:event_JCBMestizosActionPerformed

    private void JCBIndigenasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCBIndigenasActionPerformed
        if(JCBIndigenas.getSelectedItem().equals("Indigenas")){
           H3=1;
        }else{
           H3=0;
        }
    }//GEN-LAST:event_JCBIndigenasActionPerformed

    private void JCBOPacificoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCBOPacificoActionPerformed
        if(JCBOPacifico.getSelectedItem().equals("O.Pacifico")){
           G1=1;
        }else{
           G1=0;
        }
    }//GEN-LAST:event_JCBOPacificoActionPerformed

    private void JCBColombiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCBColombiaActionPerformed
        if(JCBColombia.getSelectedItem().equals("Colombia")){
           G2=1;
        }else{
           G2=0;
        }
    }//GEN-LAST:event_JCBColombiaActionPerformed

    private void JCBPeruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCBPeruActionPerformed
        if(JCBPeru.getSelectedItem().equals("Peru")){
           G3=1;
        }else{
           G3=0;
        }
    }//GEN-LAST:event_JCBPeruActionPerformed

    private void JB1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JB1MouseDragged

    }//GEN-LAST:event_JB1MouseDragged

    private void JBSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBSiguienteActionPerformed
        if(contador<8){
        JBSiguiente.setText("Siguiente Pregunta");
        contador ++;
        jTabbedPane1.setSelectedIndex(contador); 
        
       }else{
        
        JBFinalizar.setVisible(true);
        JBFinalizar.setEnabled(true);
        JBSiguiente.setEnabled(false);
        JBSiguiente.setVisible(false);
        }
        if(contador == 1){
            JB1.setBackground(green);
        }if(contador==2){
            JB2.setBackground(green);
        }if(contador==3){
            JB3.setBackground(green);
        }if(contador==4){
            JB4.setBackground(green);
        }if(contador==5){
            JB5.setBackground(green);
        }if(contador==6){
            JB6.setBackground(green);
        }if(contador==7){
            JB7.setBackground(green);
        }if(contador==8){
            JB8.setBackground(green);
        }
    }//GEN-LAST:event_JBSiguienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmSociales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmSociales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmSociales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmSociales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmSociales().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JB1;
    private javax.swing.JButton JB2;
    private javax.swing.JButton JB3;
    private javax.swing.JButton JB4;
    private javax.swing.JButton JB5;
    private javax.swing.JButton JB6;
    private javax.swing.JButton JB7;
    private javax.swing.JButton JB8;
    private javax.swing.JButton JBEstrella;
    private javax.swing.JButton JBFinalizar;
    private javax.swing.JButton JBPlaneta;
    private javax.swing.JButton JBSatelite;
    private javax.swing.JButton JBSiguiente;
    private javax.swing.JComboBox<String> JCBBlancos;
    private javax.swing.JComboBox<String> JCBColombia;
    private javax.swing.JComboBox<String> JCBEloro;
    private javax.swing.JComboBox<String> JCBEsmeraldas;
    private javax.swing.JComboBox<String> JCBGuayas;
    private javax.swing.JComboBox<String> JCBIndigenas;
    private javax.swing.JComboBox<String> JCBManabi;
    private javax.swing.JComboBox<String> JCBMestizos;
    private javax.swing.JComboBox<String> JCBOPacifico;
    private javax.swing.JComboBox<String> JCBPeru;
    private javax.swing.JLabel JLActividad1;
    private javax.swing.JLabel JLActividad2;
    private javax.swing.JLabel JLActividad3;
    private javax.swing.JLabel JLActividad4;
    private javax.swing.JLabel JLActividad5;
    private javax.swing.JLabel JLActividad6;
    private javax.swing.JLabel JLActividad7;
    private javax.swing.JLabel JLActividad8;
    private javax.swing.JLabel JLCostitucion;
    private javax.swing.JLabel JLCostumbre;
    private javax.swing.JLabel JLCuidar;
    private javax.swing.JLabel JLCumplir;
    private javax.swing.JLabel JLEcuador;
    private javax.swing.JLabel JLEducacion;
    private javax.swing.JLabel JLEscudo;
    private javax.swing.JLabel JLFamilia;
    private javax.swing.JLabel JLFlora;
    private javax.swing.JLabel JLI1;
    private javax.swing.JLabel JLI2;
    private javax.swing.JLabel JLI3;
    private javax.swing.JLabel JLI4;
    private javax.swing.JLabel JLI5;
    private javax.swing.JLabel JLImagen1;
    private javax.swing.JLabel JLImagenEste;
    private javax.swing.JLabel JLImagenLuna;
    private javax.swing.JLabel JLImagenNorte;
    private javax.swing.JLabel JLImagenOeste;
    private javax.swing.JLabel JLImagenSol;
    private javax.swing.JLabel JLImagenSur;
    private javax.swing.JLabel JLImagenTierra;
    private javax.swing.JLabel JLLimitacion;
    private javax.swing.JLabel JLMachu;
    private javax.swing.JLabel JLPiramide;
    private javax.swing.JLabel JLPregunta1;
    private javax.swing.JLabel JLPregunta2;
    private javax.swing.JLabel JLPregunta3;
    private javax.swing.JLabel JLPregunta4;
    private javax.swing.JLabel JLPregunta5;
    private javax.swing.JLabel JLPregunta6;
    private javax.swing.JLabel JLPregunta7;
    private javax.swing.JLabel JLPregunta8;
    private javax.swing.JLabel JLRespeto;
    private javax.swing.JLabel JLSalud;
    private javax.swing.JLabel JLTexto1;
    private javax.swing.JLabel JLTexto2;
    private javax.swing.JLabel JLTexto3;
    private javax.swing.JLabel JLTexto4;
    private javax.swing.JLabel JLTexto5;
    private javax.swing.JLabel JLTexto7;
    private javax.swing.JLabel JLbandera;
    private javax.swing.JPanel JPCuidar;
    private javax.swing.JPanel JPE;
    private javax.swing.JPanel JPE1;
    private javax.swing.JPanel JPE2;
    private javax.swing.JPanel JPEducacion;
    private javax.swing.JPanel JPEste;
    private javax.swing.JPanel JPFamilia;
    private javax.swing.JPanel JPI1;
    private javax.swing.JPanel JPI2;
    private javax.swing.JPanel JPI3;
    private javax.swing.JPanel JPI4;
    private javax.swing.JPanel JPI5;
    private javax.swing.JPanel JPM;
    private javax.swing.JPanel JPM1;
    private javax.swing.JPanel JPM2;
    private javax.swing.JPanel JPNorte;
    private javax.swing.JPanel JPOeste;
    private javax.swing.JPanel JPRespeto;
    private javax.swing.JPanel JPSalud;
    private javax.swing.JPanel JPSur;
    private javax.swing.JPanel JPTareas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables

    

}
